package block

// piston_push.go — the PushReaction table for the PISTON port (redstone tier-3), a 1:1 read of
// each block's BlockBehaviour.Properties.pushReaction field from the unobfuscated 26.2 jar
// (temp/cache/26.2-inner.jar). Vanilla stores the reaction on the block's Properties (default
// PushReaction.NORMAL); NO block subclass overrides BlockBehaviour.getPistonPushReaction() in 26.2
// (verified: a scan of every net.minecraft.world.level.block.*Block class found zero overrides), so
// the reaction is fully determined by the Properties field set in net.minecraft.world.level.block.Blocks
// (the explicit `.pushReaction(...)` calls plus the shared property helpers buttonProperties/
// candleProperties/flowerPotProperties/leavesProperties/pistonProperties/shulkerBoxProperties).
//
// The table below lists ONLY the non-NORMAL blocks (312 DESTROY, 13 BLOCK, 16 PUSH_ONLY = 341);
// every other block reads the NORMAL default. It was extracted this session by parsing the
// CFR-decompiled Blocks class (each `register(...)`/`registerBlocks(...)` statement's pushReaction,
// resolving the six property-helper methods and expanding the DYED_* ColorCollections to their 16
// dye colors) and cross-validated against block.StateList so every key is a real 26.2 block id.
//
// CITE: net.minecraft.world.level.material.PushReaction (NORMAL/DESTROY/BLOCK/PUSH_ONLY/IGNORE);
//   BlockBehaviour$Properties.pushReaction / BlockBehaviour.getPistonPushReaction;
//   net.minecraft.world.level.block.Blocks.<clinit> (the per-block pushReaction assignments).

// PushReaction is net.minecraft.world.level.material.PushReaction: how a block reacts to being
// pushed/pulled by a piston. NORMAL moves; DESTROY is broken (dropped) when pushed; BLOCK is
// immovable (stops the piston); PUSH_ONLY moves only when pushed (never pulled). IGNORE is an
// entity-only value (never a block reaction) and is not represented here. CITE: PushReaction.
type PushReaction byte

const (
	PushReactionNormal   PushReaction = iota // NORMAL — the default; moved and pulled normally
	PushReactionDestroy                      // DESTROY — broken + dropped when a piston pushes it
	PushReactionBlock                        // BLOCK — immovable; a piston will not move it
	PushReactionPushOnly                     // PUSH_ONLY — moved when pushed, never pulled
)

// pistonPushReactions maps a block resource id (Block.ID(), e.g. "minecraft:slime_block") to its
// non-NORMAL PushReaction. Keyed per-block (not per-state) because pushReaction is a Properties
// field shared by every state of a block in vanilla 26.2. A block absent from the map reads
// PushReactionNormal (the vanilla default). CITE: Blocks.<clinit> pushReaction assignments.
var pistonPushReactions = map[string]PushReaction{
	"minecraft:acacia_button":                      PushReactionDestroy,
	"minecraft:acacia_door":                        PushReactionDestroy,
	"minecraft:acacia_leaves":                      PushReactionDestroy,
	"minecraft:acacia_pressure_plate":              PushReactionDestroy,
	"minecraft:acacia_sapling":                     PushReactionDestroy,
	"minecraft:allium":                             PushReactionDestroy,
	"minecraft:amethyst_cluster":                   PushReactionDestroy,
	"minecraft:anvil":                              PushReactionBlock,
	"minecraft:attached_melon_stem":                PushReactionDestroy,
	"minecraft:attached_pumpkin_stem":              PushReactionDestroy,
	"minecraft:azalea":                             PushReactionDestroy,
	"minecraft:azalea_leaves":                      PushReactionDestroy,
	"minecraft:azure_bluet":                        PushReactionDestroy,
	"minecraft:bamboo":                             PushReactionDestroy,
	"minecraft:bamboo_button":                      PushReactionDestroy,
	"minecraft:bamboo_door":                        PushReactionDestroy,
	"minecraft:bamboo_pressure_plate":              PushReactionDestroy,
	"minecraft:bamboo_sapling":                     PushReactionDestroy,
	"minecraft:barrier":                            PushReactionBlock,
	"minecraft:beetroots":                          PushReactionDestroy,
	"minecraft:bell":                               PushReactionDestroy,
	"minecraft:big_dripleaf":                       PushReactionDestroy,
	"minecraft:big_dripleaf_stem":                  PushReactionDestroy,
	"minecraft:birch_button":                       PushReactionDestroy,
	"minecraft:birch_door":                         PushReactionDestroy,
	"minecraft:birch_leaves":                       PushReactionDestroy,
	"minecraft:birch_pressure_plate":               PushReactionDestroy,
	"minecraft:birch_sapling":                      PushReactionDestroy,
	"minecraft:black_bed":                          PushReactionDestroy,
	"minecraft:black_candle":                       PushReactionDestroy,
	"minecraft:black_glazed_terracotta":            PushReactionPushOnly,
	"minecraft:black_shulker_box":                  PushReactionDestroy,
	"minecraft:blue_bed":                           PushReactionDestroy,
	"minecraft:blue_candle":                        PushReactionDestroy,
	"minecraft:blue_glazed_terracotta":             PushReactionPushOnly,
	"minecraft:blue_orchid":                        PushReactionDestroy,
	"minecraft:blue_shulker_box":                   PushReactionDestroy,
	"minecraft:brain_coral":                        PushReactionDestroy,
	"minecraft:brain_coral_fan":                    PushReactionDestroy,
	"minecraft:brain_coral_wall_fan":               PushReactionDestroy,
	"minecraft:brown_bed":                          PushReactionDestroy,
	"minecraft:brown_candle":                       PushReactionDestroy,
	"minecraft:brown_glazed_terracotta":            PushReactionPushOnly,
	"minecraft:brown_mushroom":                     PushReactionDestroy,
	"minecraft:brown_shulker_box":                  PushReactionDestroy,
	"minecraft:bubble_column":                      PushReactionDestroy,
	"minecraft:bubble_coral":                       PushReactionDestroy,
	"minecraft:bubble_coral_fan":                   PushReactionDestroy,
	"minecraft:bubble_coral_wall_fan":              PushReactionDestroy,
	"minecraft:budding_amethyst":                   PushReactionDestroy,
	"minecraft:bush":                               PushReactionDestroy,
	"minecraft:cactus":                             PushReactionDestroy,
	"minecraft:cactus_flower":                      PushReactionDestroy,
	"minecraft:cake":                               PushReactionDestroy,
	"minecraft:candle":                             PushReactionDestroy,
	"minecraft:carrots":                            PushReactionDestroy,
	"minecraft:carved_pumpkin":                     PushReactionDestroy,
	"minecraft:cave_vines":                         PushReactionDestroy,
	"minecraft:cave_vines_plant":                   PushReactionDestroy,
	"minecraft:cherry_button":                      PushReactionDestroy,
	"minecraft:cherry_door":                        PushReactionDestroy,
	"minecraft:cherry_leaves":                      PushReactionDestroy,
	"minecraft:cherry_pressure_plate":              PushReactionDestroy,
	"minecraft:cherry_sapling":                     PushReactionDestroy,
	"minecraft:chipped_anvil":                      PushReactionBlock,
	"minecraft:chorus_flower":                      PushReactionDestroy,
	"minecraft:chorus_plant":                       PushReactionDestroy,
	"minecraft:closed_eyeblossom":                  PushReactionDestroy,
	"minecraft:cobweb":                             PushReactionDestroy,
	"minecraft:cocoa":                              PushReactionDestroy,
	"minecraft:comparator":                         PushReactionDestroy,
	"minecraft:copper_torch":                       PushReactionDestroy,
	"minecraft:copper_wall_torch":                  PushReactionDestroy,
	"minecraft:cornflower":                         PushReactionDestroy,
	"minecraft:creeper_head":                       PushReactionDestroy,
	"minecraft:creeper_wall_head":                  PushReactionDestroy,
	"minecraft:crimson_button":                     PushReactionDestroy,
	"minecraft:crimson_door":                       PushReactionDestroy,
	"minecraft:crimson_fungus":                     PushReactionDestroy,
	"minecraft:crimson_pressure_plate":             PushReactionDestroy,
	"minecraft:crimson_roots":                      PushReactionDestroy,
	"minecraft:cyan_bed":                           PushReactionDestroy,
	"minecraft:cyan_candle":                        PushReactionDestroy,
	"minecraft:cyan_glazed_terracotta":             PushReactionPushOnly,
	"minecraft:cyan_shulker_box":                   PushReactionDestroy,
	"minecraft:damaged_anvil":                      PushReactionBlock,
	"minecraft:dandelion":                          PushReactionDestroy,
	"minecraft:dark_oak_button":                    PushReactionDestroy,
	"minecraft:dark_oak_door":                      PushReactionDestroy,
	"minecraft:dark_oak_leaves":                    PushReactionDestroy,
	"minecraft:dark_oak_pressure_plate":            PushReactionDestroy,
	"minecraft:dark_oak_sapling":                   PushReactionDestroy,
	"minecraft:dead_bush":                          PushReactionDestroy,
	"minecraft:decorated_pot":                      PushReactionDestroy,
	"minecraft:dragon_egg":                         PushReactionDestroy,
	"minecraft:dragon_head":                        PushReactionDestroy,
	"minecraft:dragon_wall_head":                   PushReactionDestroy,
	"minecraft:end_gateway":                        PushReactionBlock,
	"minecraft:end_portal":                         PushReactionBlock,
	"minecraft:fern":                               PushReactionDestroy,
	"minecraft:fire":                               PushReactionDestroy,
	"minecraft:fire_coral":                         PushReactionDestroy,
	"minecraft:fire_coral_fan":                     PushReactionDestroy,
	"minecraft:fire_coral_wall_fan":                PushReactionDestroy,
	"minecraft:firefly_bush":                       PushReactionDestroy,
	"minecraft:flower_pot":                         PushReactionDestroy,
	"minecraft:flowering_azalea":                   PushReactionDestroy,
	"minecraft:flowering_azalea_leaves":            PushReactionDestroy,
	"minecraft:frogspawn":                          PushReactionDestroy,
	"minecraft:glow_lichen":                        PushReactionDestroy,
	"minecraft:golden_dandelion":                   PushReactionDestroy,
	"minecraft:gray_bed":                           PushReactionDestroy,
	"minecraft:gray_candle":                        PushReactionDestroy,
	"minecraft:gray_glazed_terracotta":             PushReactionPushOnly,
	"minecraft:gray_shulker_box":                   PushReactionDestroy,
	"minecraft:green_bed":                          PushReactionDestroy,
	"minecraft:green_candle":                       PushReactionDestroy,
	"minecraft:green_glazed_terracotta":            PushReactionPushOnly,
	"minecraft:green_shulker_box":                  PushReactionDestroy,
	"minecraft:grindstone":                         PushReactionBlock,
	"minecraft:hanging_roots":                      PushReactionDestroy,
	"minecraft:heavy_weighted_pressure_plate":      PushReactionDestroy,
	"minecraft:horn_coral":                         PushReactionDestroy,
	"minecraft:horn_coral_fan":                     PushReactionDestroy,
	"minecraft:horn_coral_wall_fan":                PushReactionDestroy,
	"minecraft:iron_door":                          PushReactionDestroy,
	"minecraft:jack_o_lantern":                     PushReactionDestroy,
	"minecraft:jungle_button":                      PushReactionDestroy,
	"minecraft:jungle_door":                        PushReactionDestroy,
	"minecraft:jungle_leaves":                      PushReactionDestroy,
	"minecraft:jungle_pressure_plate":              PushReactionDestroy,
	"minecraft:jungle_sapling":                     PushReactionDestroy,
	"minecraft:kelp":                               PushReactionDestroy,
	"minecraft:kelp_plant":                         PushReactionDestroy,
	"minecraft:ladder":                             PushReactionDestroy,
	"minecraft:lantern":                            PushReactionDestroy,
	"minecraft:large_fern":                         PushReactionDestroy,
	"minecraft:lava":                               PushReactionDestroy,
	"minecraft:leaf_litter":                        PushReactionDestroy,
	"minecraft:lever":                              PushReactionDestroy,
	"minecraft:light_blue_bed":                     PushReactionDestroy,
	"minecraft:light_blue_candle":                  PushReactionDestroy,
	"minecraft:light_blue_glazed_terracotta":       PushReactionPushOnly,
	"minecraft:light_blue_shulker_box":             PushReactionDestroy,
	"minecraft:light_gray_bed":                     PushReactionDestroy,
	"minecraft:light_gray_candle":                  PushReactionDestroy,
	"minecraft:light_gray_glazed_terracotta":       PushReactionPushOnly,
	"minecraft:light_gray_shulker_box":             PushReactionDestroy,
	"minecraft:light_weighted_pressure_plate":      PushReactionDestroy,
	"minecraft:lilac":                              PushReactionDestroy,
	"minecraft:lily_of_the_valley":                 PushReactionDestroy,
	"minecraft:lily_pad":                           PushReactionDestroy,
	"minecraft:lime_bed":                           PushReactionDestroy,
	"minecraft:lime_candle":                        PushReactionDestroy,
	"minecraft:lime_glazed_terracotta":             PushReactionPushOnly,
	"minecraft:lime_shulker_box":                   PushReactionDestroy,
	"minecraft:lodestone":                          PushReactionBlock,
	"minecraft:magenta_bed":                        PushReactionDestroy,
	"minecraft:magenta_candle":                     PushReactionDestroy,
	"minecraft:magenta_glazed_terracotta":          PushReactionPushOnly,
	"minecraft:magenta_shulker_box":                PushReactionDestroy,
	"minecraft:mangrove_button":                    PushReactionDestroy,
	"minecraft:mangrove_door":                      PushReactionDestroy,
	"minecraft:mangrove_leaves":                    PushReactionDestroy,
	"minecraft:mangrove_pressure_plate":            PushReactionDestroy,
	"minecraft:mangrove_propagule":                 PushReactionDestroy,
	"minecraft:melon":                              PushReactionDestroy,
	"minecraft:melon_stem":                         PushReactionDestroy,
	"minecraft:moss_block":                         PushReactionDestroy,
	"minecraft:moss_carpet":                        PushReactionDestroy,
	"minecraft:moving_piston":                      PushReactionBlock,
	"minecraft:nether_portal":                      PushReactionBlock,
	"minecraft:nether_sprouts":                     PushReactionDestroy,
	"minecraft:nether_wart":                        PushReactionDestroy,
	"minecraft:oak_button":                         PushReactionDestroy,
	"minecraft:oak_door":                           PushReactionDestroy,
	"minecraft:oak_leaves":                         PushReactionDestroy,
	"minecraft:oak_pressure_plate":                 PushReactionDestroy,
	"minecraft:oak_sapling":                        PushReactionDestroy,
	"minecraft:open_eyeblossom":                    PushReactionDestroy,
	"minecraft:orange_bed":                         PushReactionDestroy,
	"minecraft:orange_candle":                      PushReactionDestroy,
	"minecraft:orange_glazed_terracotta":           PushReactionPushOnly,
	"minecraft:orange_shulker_box":                 PushReactionDestroy,
	"minecraft:orange_tulip":                       PushReactionDestroy,
	"minecraft:oxeye_daisy":                        PushReactionDestroy,
	"minecraft:pale_hanging_moss":                  PushReactionDestroy,
	"minecraft:pale_moss_block":                    PushReactionDestroy,
	"minecraft:pale_moss_carpet":                   PushReactionDestroy,
	"minecraft:pale_oak_button":                    PushReactionDestroy,
	"minecraft:pale_oak_door":                      PushReactionDestroy,
	"minecraft:pale_oak_leaves":                    PushReactionDestroy,
	"minecraft:pale_oak_pressure_plate":            PushReactionDestroy,
	"minecraft:pale_oak_sapling":                   PushReactionDestroy,
	"minecraft:peony":                              PushReactionDestroy,
	"minecraft:piglin_head":                        PushReactionDestroy,
	"minecraft:piglin_wall_head":                   PushReactionDestroy,
	"minecraft:pink_bed":                           PushReactionDestroy,
	"minecraft:pink_candle":                        PushReactionDestroy,
	"minecraft:pink_glazed_terracotta":             PushReactionPushOnly,
	"minecraft:pink_petals":                        PushReactionDestroy,
	"minecraft:pink_shulker_box":                   PushReactionDestroy,
	"minecraft:pink_tulip":                         PushReactionDestroy,
	"minecraft:piston":                             PushReactionBlock,
	"minecraft:piston_head":                        PushReactionBlock,
	"minecraft:pitcher_crop":                       PushReactionDestroy,
	"minecraft:pitcher_plant":                      PushReactionDestroy,
	"minecraft:player_head":                        PushReactionDestroy,
	"minecraft:player_wall_head":                   PushReactionDestroy,
	"minecraft:pointed_dripstone":                  PushReactionDestroy,
	"minecraft:polished_blackstone_button":         PushReactionDestroy,
	"minecraft:polished_blackstone_pressure_plate": PushReactionDestroy,
	"minecraft:poppy":                              PushReactionDestroy,
	"minecraft:potatoes":                           PushReactionDestroy,
	"minecraft:potted_acacia_sapling":              PushReactionDestroy,
	"minecraft:potted_allium":                      PushReactionDestroy,
	"minecraft:potted_azalea_bush":                 PushReactionDestroy,
	"minecraft:potted_azure_bluet":                 PushReactionDestroy,
	"minecraft:potted_bamboo":                      PushReactionDestroy,
	"minecraft:potted_birch_sapling":               PushReactionDestroy,
	"minecraft:potted_blue_orchid":                 PushReactionDestroy,
	"minecraft:potted_brown_mushroom":              PushReactionDestroy,
	"minecraft:potted_cactus":                      PushReactionDestroy,
	"minecraft:potted_cherry_sapling":              PushReactionDestroy,
	"minecraft:potted_closed_eyeblossom":           PushReactionDestroy,
	"minecraft:potted_cornflower":                  PushReactionDestroy,
	"minecraft:potted_crimson_fungus":              PushReactionDestroy,
	"minecraft:potted_crimson_roots":               PushReactionDestroy,
	"minecraft:potted_dandelion":                   PushReactionDestroy,
	"minecraft:potted_dark_oak_sapling":            PushReactionDestroy,
	"minecraft:potted_dead_bush":                   PushReactionDestroy,
	"minecraft:potted_fern":                        PushReactionDestroy,
	"minecraft:potted_flowering_azalea_bush":       PushReactionDestroy,
	"minecraft:potted_golden_dandelion":            PushReactionDestroy,
	"minecraft:potted_jungle_sapling":              PushReactionDestroy,
	"minecraft:potted_lily_of_the_valley":          PushReactionDestroy,
	"minecraft:potted_mangrove_propagule":          PushReactionDestroy,
	"minecraft:potted_oak_sapling":                 PushReactionDestroy,
	"minecraft:potted_open_eyeblossom":             PushReactionDestroy,
	"minecraft:potted_orange_tulip":                PushReactionDestroy,
	"minecraft:potted_oxeye_daisy":                 PushReactionDestroy,
	"minecraft:potted_pale_oak_sapling":            PushReactionDestroy,
	"minecraft:potted_pink_tulip":                  PushReactionDestroy,
	"minecraft:potted_poppy":                       PushReactionDestroy,
	"minecraft:potted_red_mushroom":                PushReactionDestroy,
	"minecraft:potted_red_tulip":                   PushReactionDestroy,
	"minecraft:potted_spruce_sapling":              PushReactionDestroy,
	"minecraft:potted_torchflower":                 PushReactionDestroy,
	"minecraft:potted_warped_fungus":               PushReactionDestroy,
	"minecraft:potted_warped_roots":                PushReactionDestroy,
	"minecraft:potted_white_tulip":                 PushReactionDestroy,
	"minecraft:potted_wither_rose":                 PushReactionDestroy,
	"minecraft:pumpkin":                            PushReactionDestroy,
	"minecraft:pumpkin_stem":                       PushReactionDestroy,
	"minecraft:purple_bed":                         PushReactionDestroy,
	"minecraft:purple_candle":                      PushReactionDestroy,
	"minecraft:purple_glazed_terracotta":           PushReactionPushOnly,
	"minecraft:purple_shulker_box":                 PushReactionDestroy,
	"minecraft:red_bed":                            PushReactionDestroy,
	"minecraft:red_candle":                         PushReactionDestroy,
	"minecraft:red_glazed_terracotta":              PushReactionPushOnly,
	"minecraft:red_mushroom":                       PushReactionDestroy,
	"minecraft:red_shulker_box":                    PushReactionDestroy,
	"minecraft:red_tulip":                          PushReactionDestroy,
	"minecraft:redstone_torch":                     PushReactionDestroy,
	"minecraft:redstone_wall_torch":                PushReactionDestroy,
	"minecraft:redstone_wire":                      PushReactionDestroy,
	"minecraft:repeater":                           PushReactionDestroy,
	"minecraft:resin_clump":                        PushReactionDestroy,
	"minecraft:rose_bush":                          PushReactionDestroy,
	"minecraft:scaffolding":                        PushReactionDestroy,
	"minecraft:sculk_vein":                         PushReactionDestroy,
	"minecraft:sea_pickle":                         PushReactionDestroy,
	"minecraft:seagrass":                           PushReactionDestroy,
	"minecraft:short_dry_grass":                    PushReactionDestroy,
	"minecraft:short_grass":                        PushReactionDestroy,
	"minecraft:shulker_box":                        PushReactionDestroy,
	"minecraft:skeleton_skull":                     PushReactionDestroy,
	"minecraft:skeleton_wall_skull":                PushReactionDestroy,
	"minecraft:small_dripleaf":                     PushReactionDestroy,
	"minecraft:snow":                               PushReactionDestroy,
	"minecraft:soul_fire":                          PushReactionDestroy,
	"minecraft:soul_lantern":                       PushReactionDestroy,
	"minecraft:soul_torch":                         PushReactionDestroy,
	"minecraft:soul_wall_torch":                    PushReactionDestroy,
	"minecraft:spore_blossom":                      PushReactionDestroy,
	"minecraft:spruce_button":                      PushReactionDestroy,
	"minecraft:spruce_door":                        PushReactionDestroy,
	"minecraft:spruce_leaves":                      PushReactionDestroy,
	"minecraft:spruce_pressure_plate":              PushReactionDestroy,
	"minecraft:spruce_sapling":                     PushReactionDestroy,
	"minecraft:sticky_piston":                      PushReactionBlock,
	"minecraft:stone_button":                       PushReactionDestroy,
	"minecraft:stone_pressure_plate":               PushReactionDestroy,
	"minecraft:structure_void":                     PushReactionDestroy,
	"minecraft:sugar_cane":                         PushReactionDestroy,
	"minecraft:sulfur_spike":                       PushReactionDestroy,
	"minecraft:sunflower":                          PushReactionDestroy,
	"minecraft:suspicious_gravel":                  PushReactionDestroy,
	"minecraft:suspicious_sand":                    PushReactionDestroy,
	"minecraft:sweet_berry_bush":                   PushReactionDestroy,
	"minecraft:tall_dry_grass":                     PushReactionDestroy,
	"minecraft:tall_grass":                         PushReactionDestroy,
	"minecraft:tall_seagrass":                      PushReactionDestroy,
	"minecraft:torch":                              PushReactionDestroy,
	"minecraft:torchflower":                        PushReactionDestroy,
	"minecraft:torchflower_crop":                   PushReactionDestroy,
	"minecraft:tripwire":                           PushReactionDestroy,
	"minecraft:tripwire_hook":                      PushReactionDestroy,
	"minecraft:tube_coral":                         PushReactionDestroy,
	"minecraft:tube_coral_fan":                     PushReactionDestroy,
	"minecraft:tube_coral_wall_fan":                PushReactionDestroy,
	"minecraft:turtle_egg":                         PushReactionDestroy,
	"minecraft:twisting_vines":                     PushReactionDestroy,
	"minecraft:twisting_vines_plant":               PushReactionDestroy,
	"minecraft:vine":                               PushReactionDestroy,
	"minecraft:wall_torch":                         PushReactionDestroy,
	"minecraft:warped_button":                      PushReactionDestroy,
	"minecraft:warped_door":                        PushReactionDestroy,
	"minecraft:warped_fungus":                      PushReactionDestroy,
	"minecraft:warped_pressure_plate":              PushReactionDestroy,
	"minecraft:warped_roots":                       PushReactionDestroy,
	"minecraft:water":                              PushReactionDestroy,
	"minecraft:weeping_vines":                      PushReactionDestroy,
	"minecraft:weeping_vines_plant":                PushReactionDestroy,
	"minecraft:wheat":                              PushReactionDestroy,
	"minecraft:white_bed":                          PushReactionDestroy,
	"minecraft:white_candle":                       PushReactionDestroy,
	"minecraft:white_glazed_terracotta":            PushReactionPushOnly,
	"minecraft:white_shulker_box":                  PushReactionDestroy,
	"minecraft:white_tulip":                        PushReactionDestroy,
	"minecraft:wildflowers":                        PushReactionDestroy,
	"minecraft:wither_rose":                        PushReactionDestroy,
	"minecraft:wither_skeleton_skull":              PushReactionDestroy,
	"minecraft:wither_skeleton_wall_skull":         PushReactionDestroy,
	"minecraft:yellow_bed":                         PushReactionDestroy,
	"minecraft:yellow_candle":                      PushReactionDestroy,
	"minecraft:yellow_glazed_terracotta":           PushReactionPushOnly,
	"minecraft:yellow_shulker_box":                 PushReactionDestroy,
	"minecraft:zombie_head":                        PushReactionDestroy,
	"minecraft:zombie_wall_head":                   PushReactionDestroy,
}

// PistonPushReaction is BlockState.getPistonPushReaction() -> BlockBehaviour.getPistonPushReaction():
// the block's PushReaction (default NORMAL). Looks the state's Block.ID() up in the non-NORMAL table;
// any block not present reads NORMAL. An out-of-range state id reads NORMAL (a defensive default that
// never makes a bad state pushable-destroy or immovable). CITE: BlockBehaviour.getPistonPushReaction
// (`return this.pushReaction`).
func PistonPushReaction(s StateID) PushReaction {
	if int(s) < 0 || int(s) >= len(StateList) {
		return PushReactionNormal
	}
	if r, ok := pistonPushReactions[StateList[s].ID()]; ok {
		return r
	}
	return PushReactionNormal
}
