// Code generated by tools/gen_tool_defaults.go from 26.2 jar block tags; DO NOT EDIT.
//
// tool_tags_gen.go merges the non-mineable block tags the Tool data component's rules reference
// (incorrect_for_*_tool, shears_*, sword_*) into BlockTags. These are recursively flattened from
// the jar's data/minecraft/tags/block/*.json (nested #needs_*_tool refs resolved, the same
// TagLoader.build semantics that produced the mineable/* tags in tags.go). They back:
//   - the Tool rule correct_for_drops gate: an incorrect_for_X_tool membership makes a tier-X tool
//     INCORRECT for that block's drops (isCorrectForDrops's first-matching-rule => false), which in
//     turn selects getDestroyProgress's 100 divisor (vs 30) — e.g. a wooden pickaxe mining iron ore.
//   - the sword/shears special mining-speed rules (sword_efficient 1.5x, sword_instantly_mines
//     Float.MAX, shears_*_breaking_speed), read by Tool.getMiningSpeed.
//
// Kept OUT-OF-BAND from tags.go (the hand-maintained BlockTags home) as a separate _gen file so the
// tool-rule tag data has one clear owner; merged via init so BlockTags stays the single lookup map.
// Cite net.minecraft.tags.BlockTags (INCORRECT_FOR_* / SWORD_EFFICIENT / SWORD_INSTANTLY_MINES /
// SHEARS_*_BREAKING_SPEED) + data/minecraft/tags/block/*.json.
package tag

func init() {
	for name, set := range toolRuleBlockTags {
		BlockTags[name] = set
	}
}

var toolRuleBlockTags = map[string]map[string]bool{
	"incorrect_for_copper_tool": {
		"minecraft:ancient_debris": true, "minecraft:crying_obsidian": true, "minecraft:deepslate_diamond_ore": true,
		"minecraft:deepslate_emerald_ore": true, "minecraft:deepslate_gold_ore": true, "minecraft:deepslate_redstone_ore": true,
		"minecraft:diamond_block": true, "minecraft:diamond_ore": true, "minecraft:emerald_block": true,
		"minecraft:emerald_ore": true, "minecraft:gold_block": true, "minecraft:gold_ore": true,
		"minecraft:netherite_block": true, "minecraft:obsidian": true, "minecraft:raw_gold_block": true,
		"minecraft:redstone_ore": true, "minecraft:respawn_anchor": true,
	},
	"incorrect_for_diamond_tool": {},
	"incorrect_for_gold_tool": {
		"minecraft:ancient_debris": true, "minecraft:chiseled_copper": true, "minecraft:copper_block": true,
		"minecraft:copper_bulb": true, "minecraft:copper_chest": true, "minecraft:copper_grate": true,
		"minecraft:copper_ore": true, "minecraft:copper_trapdoor": true, "minecraft:crafter": true,
		"minecraft:crying_obsidian": true, "minecraft:cut_copper": true, "minecraft:cut_copper_slab": true,
		"minecraft:cut_copper_stairs": true, "minecraft:deepslate_copper_ore": true, "minecraft:deepslate_diamond_ore": true,
		"minecraft:deepslate_emerald_ore": true, "minecraft:deepslate_gold_ore": true, "minecraft:deepslate_iron_ore": true,
		"minecraft:deepslate_lapis_ore": true, "minecraft:deepslate_redstone_ore": true, "minecraft:diamond_block": true,
		"minecraft:diamond_ore": true, "minecraft:emerald_block": true, "minecraft:emerald_ore": true,
		"minecraft:exposed_chiseled_copper": true, "minecraft:exposed_copper": true, "minecraft:exposed_copper_bulb": true,
		"minecraft:exposed_copper_chest": true, "minecraft:exposed_copper_grate": true, "minecraft:exposed_copper_trapdoor": true,
		"minecraft:exposed_cut_copper": true, "minecraft:exposed_cut_copper_slab": true, "minecraft:exposed_cut_copper_stairs": true,
		"minecraft:exposed_lightning_rod": true, "minecraft:gold_block": true, "minecraft:gold_ore": true,
		"minecraft:iron_block": true, "minecraft:iron_ore": true, "minecraft:lapis_block": true,
		"minecraft:lapis_ore": true, "minecraft:lightning_rod": true, "minecraft:netherite_block": true,
		"minecraft:obsidian": true, "minecraft:oxidized_chiseled_copper": true, "minecraft:oxidized_copper": true,
		"minecraft:oxidized_copper_bulb": true, "minecraft:oxidized_copper_chest": true, "minecraft:oxidized_copper_grate": true,
		"minecraft:oxidized_copper_trapdoor": true, "minecraft:oxidized_cut_copper": true, "minecraft:oxidized_cut_copper_slab": true,
		"minecraft:oxidized_cut_copper_stairs": true, "minecraft:oxidized_lightning_rod": true, "minecraft:raw_copper_block": true,
		"minecraft:raw_gold_block": true, "minecraft:raw_iron_block": true, "minecraft:redstone_ore": true,
		"minecraft:respawn_anchor": true, "minecraft:waxed_chiseled_copper": true, "minecraft:waxed_copper_block": true,
		"minecraft:waxed_copper_bulb": true, "minecraft:waxed_copper_chest": true, "minecraft:waxed_copper_grate": true,
		"minecraft:waxed_copper_trapdoor": true, "minecraft:waxed_cut_copper": true, "minecraft:waxed_cut_copper_slab": true,
		"minecraft:waxed_cut_copper_stairs": true, "minecraft:waxed_exposed_chiseled_copper": true, "minecraft:waxed_exposed_copper": true,
		"minecraft:waxed_exposed_copper_bulb": true, "minecraft:waxed_exposed_copper_chest": true, "minecraft:waxed_exposed_copper_grate": true,
		"minecraft:waxed_exposed_copper_trapdoor": true, "minecraft:waxed_exposed_cut_copper": true, "minecraft:waxed_exposed_cut_copper_slab": true,
		"minecraft:waxed_exposed_cut_copper_stairs": true, "minecraft:waxed_exposed_lightning_rod": true, "minecraft:waxed_lightning_rod": true,
		"minecraft:waxed_oxidized_chiseled_copper": true, "minecraft:waxed_oxidized_copper": true, "minecraft:waxed_oxidized_copper_bulb": true,
		"minecraft:waxed_oxidized_copper_chest": true, "minecraft:waxed_oxidized_copper_grate": true, "minecraft:waxed_oxidized_copper_trapdoor": true,
		"minecraft:waxed_oxidized_cut_copper": true, "minecraft:waxed_oxidized_cut_copper_slab": true, "minecraft:waxed_oxidized_cut_copper_stairs": true,
		"minecraft:waxed_oxidized_lightning_rod": true, "minecraft:waxed_weathered_chiseled_copper": true, "minecraft:waxed_weathered_copper": true,
		"minecraft:waxed_weathered_copper_bulb": true, "minecraft:waxed_weathered_copper_chest": true, "minecraft:waxed_weathered_copper_grate": true,
		"minecraft:waxed_weathered_copper_trapdoor": true, "minecraft:waxed_weathered_cut_copper": true, "minecraft:waxed_weathered_cut_copper_slab": true,
		"minecraft:waxed_weathered_cut_copper_stairs": true, "minecraft:waxed_weathered_lightning_rod": true, "minecraft:weathered_chiseled_copper": true,
		"minecraft:weathered_copper": true, "minecraft:weathered_copper_bulb": true, "minecraft:weathered_copper_chest": true,
		"minecraft:weathered_copper_grate": true, "minecraft:weathered_copper_trapdoor": true, "minecraft:weathered_cut_copper": true,
		"minecraft:weathered_cut_copper_slab": true, "minecraft:weathered_cut_copper_stairs": true, "minecraft:weathered_lightning_rod": true,
	},
	"incorrect_for_iron_tool": {
		"minecraft:ancient_debris": true, "minecraft:crying_obsidian": true, "minecraft:netherite_block": true,
		"minecraft:obsidian": true, "minecraft:respawn_anchor": true,
	},
	"incorrect_for_netherite_tool": {},
	"incorrect_for_stone_tool": {
		"minecraft:ancient_debris": true, "minecraft:crying_obsidian": true, "minecraft:deepslate_diamond_ore": true,
		"minecraft:deepslate_emerald_ore": true, "minecraft:deepslate_gold_ore": true, "minecraft:deepslate_redstone_ore": true,
		"minecraft:diamond_block": true, "minecraft:diamond_ore": true, "minecraft:emerald_block": true,
		"minecraft:emerald_ore": true, "minecraft:gold_block": true, "minecraft:gold_ore": true,
		"minecraft:netherite_block": true, "minecraft:obsidian": true, "minecraft:raw_gold_block": true,
		"minecraft:redstone_ore": true, "minecraft:respawn_anchor": true,
	},
	"incorrect_for_wooden_tool": {
		"minecraft:ancient_debris": true, "minecraft:chiseled_copper": true, "minecraft:copper_block": true,
		"minecraft:copper_bulb": true, "minecraft:copper_chest": true, "minecraft:copper_grate": true,
		"minecraft:copper_ore": true, "minecraft:copper_trapdoor": true, "minecraft:crafter": true,
		"minecraft:crying_obsidian": true, "minecraft:cut_copper": true, "minecraft:cut_copper_slab": true,
		"minecraft:cut_copper_stairs": true, "minecraft:deepslate_copper_ore": true, "minecraft:deepslate_diamond_ore": true,
		"minecraft:deepslate_emerald_ore": true, "minecraft:deepslate_gold_ore": true, "minecraft:deepslate_iron_ore": true,
		"minecraft:deepslate_lapis_ore": true, "minecraft:deepslate_redstone_ore": true, "minecraft:diamond_block": true,
		"minecraft:diamond_ore": true, "minecraft:emerald_block": true, "minecraft:emerald_ore": true,
		"minecraft:exposed_chiseled_copper": true, "minecraft:exposed_copper": true, "minecraft:exposed_copper_bulb": true,
		"minecraft:exposed_copper_chest": true, "minecraft:exposed_copper_grate": true, "minecraft:exposed_copper_trapdoor": true,
		"minecraft:exposed_cut_copper": true, "minecraft:exposed_cut_copper_slab": true, "minecraft:exposed_cut_copper_stairs": true,
		"minecraft:exposed_lightning_rod": true, "minecraft:gold_block": true, "minecraft:gold_ore": true,
		"minecraft:iron_block": true, "minecraft:iron_ore": true, "minecraft:lapis_block": true,
		"minecraft:lapis_ore": true, "minecraft:lightning_rod": true, "minecraft:netherite_block": true,
		"minecraft:obsidian": true, "minecraft:oxidized_chiseled_copper": true, "minecraft:oxidized_copper": true,
		"minecraft:oxidized_copper_bulb": true, "minecraft:oxidized_copper_chest": true, "minecraft:oxidized_copper_grate": true,
		"minecraft:oxidized_copper_trapdoor": true, "minecraft:oxidized_cut_copper": true, "minecraft:oxidized_cut_copper_slab": true,
		"minecraft:oxidized_cut_copper_stairs": true, "minecraft:oxidized_lightning_rod": true, "minecraft:raw_copper_block": true,
		"minecraft:raw_gold_block": true, "minecraft:raw_iron_block": true, "minecraft:redstone_ore": true,
		"minecraft:respawn_anchor": true, "minecraft:waxed_chiseled_copper": true, "minecraft:waxed_copper_block": true,
		"minecraft:waxed_copper_bulb": true, "minecraft:waxed_copper_chest": true, "minecraft:waxed_copper_grate": true,
		"minecraft:waxed_copper_trapdoor": true, "minecraft:waxed_cut_copper": true, "minecraft:waxed_cut_copper_slab": true,
		"minecraft:waxed_cut_copper_stairs": true, "minecraft:waxed_exposed_chiseled_copper": true, "minecraft:waxed_exposed_copper": true,
		"minecraft:waxed_exposed_copper_bulb": true, "minecraft:waxed_exposed_copper_chest": true, "minecraft:waxed_exposed_copper_grate": true,
		"minecraft:waxed_exposed_copper_trapdoor": true, "minecraft:waxed_exposed_cut_copper": true, "minecraft:waxed_exposed_cut_copper_slab": true,
		"minecraft:waxed_exposed_cut_copper_stairs": true, "minecraft:waxed_exposed_lightning_rod": true, "minecraft:waxed_lightning_rod": true,
		"minecraft:waxed_oxidized_chiseled_copper": true, "minecraft:waxed_oxidized_copper": true, "minecraft:waxed_oxidized_copper_bulb": true,
		"minecraft:waxed_oxidized_copper_chest": true, "minecraft:waxed_oxidized_copper_grate": true, "minecraft:waxed_oxidized_copper_trapdoor": true,
		"minecraft:waxed_oxidized_cut_copper": true, "minecraft:waxed_oxidized_cut_copper_slab": true, "minecraft:waxed_oxidized_cut_copper_stairs": true,
		"minecraft:waxed_oxidized_lightning_rod": true, "minecraft:waxed_weathered_chiseled_copper": true, "minecraft:waxed_weathered_copper": true,
		"minecraft:waxed_weathered_copper_bulb": true, "minecraft:waxed_weathered_copper_chest": true, "minecraft:waxed_weathered_copper_grate": true,
		"minecraft:waxed_weathered_copper_trapdoor": true, "minecraft:waxed_weathered_cut_copper": true, "minecraft:waxed_weathered_cut_copper_slab": true,
		"minecraft:waxed_weathered_cut_copper_stairs": true, "minecraft:waxed_weathered_lightning_rod": true, "minecraft:weathered_chiseled_copper": true,
		"minecraft:weathered_copper": true, "minecraft:weathered_copper_bulb": true, "minecraft:weathered_copper_chest": true,
		"minecraft:weathered_copper_grate": true, "minecraft:weathered_copper_trapdoor": true, "minecraft:weathered_cut_copper": true,
		"minecraft:weathered_cut_copper_slab": true, "minecraft:weathered_cut_copper_stairs": true, "minecraft:weathered_lightning_rod": true,
	},
	"shears_extreme_breaking_speed": {
		"minecraft:acacia_leaves": true, "minecraft:azalea_leaves": true, "minecraft:birch_leaves": true,
		"minecraft:cherry_leaves": true, "minecraft:dark_oak_leaves": true, "minecraft:flowering_azalea_leaves": true,
		"minecraft:jungle_leaves": true, "minecraft:mangrove_leaves": true, "minecraft:oak_leaves": true,
		"minecraft:pale_oak_leaves": true, "minecraft:spruce_leaves": true,
	},
	"shears_major_breaking_speed": {
		"minecraft:black_wool": true, "minecraft:blue_wool": true, "minecraft:brown_wool": true,
		"minecraft:cyan_wool": true, "minecraft:gray_wool": true, "minecraft:green_wool": true,
		"minecraft:light_blue_wool": true, "minecraft:light_gray_wool": true, "minecraft:lime_wool": true,
		"minecraft:magenta_wool": true, "minecraft:orange_wool": true, "minecraft:pink_wool": true,
		"minecraft:purple_wool": true, "minecraft:red_wool": true, "minecraft:white_wool": true,
		"minecraft:yellow_wool": true,
	},
	"shears_minor_breaking_speed": {
		"minecraft:glow_lichen": true, "minecraft:vine": true,
	},
	"sword_efficient": {
		"minecraft:acacia_leaves": true, "minecraft:azalea_leaves": true, "minecraft:big_dripleaf": true,
		"minecraft:big_dripleaf_stem": true, "minecraft:birch_leaves": true, "minecraft:carved_pumpkin": true,
		"minecraft:cherry_leaves": true, "minecraft:chorus_flower": true, "minecraft:chorus_plant": true,
		"minecraft:cocoa": true, "minecraft:dark_oak_leaves": true, "minecraft:flowering_azalea_leaves": true,
		"minecraft:glow_lichen": true, "minecraft:jack_o_lantern": true, "minecraft:jungle_leaves": true,
		"minecraft:mangrove_leaves": true, "minecraft:melon": true, "minecraft:oak_leaves": true,
		"minecraft:pale_oak_leaves": true, "minecraft:pumpkin": true, "minecraft:spruce_leaves": true,
		"minecraft:vine": true,
	},
	"sword_instantly_mines": {
		"minecraft:bamboo": true, "minecraft:bamboo_sapling": true,
	},
}
