// Code generated by tools/gen_item_attribute_modifiers.go from 26.2/items.json; DO NOT EDIT.

package item

// ItemAttributeModifier is one entry of an item's default minecraft:attribute_modifiers
// component (net.minecraft.world.item.component.ItemAttributeModifiers$Entry): the attribute it
// targets, the AttributeModifier record (id, amount, operation) and the EquipmentSlotGroup the
// entry applies in. ItemStack.forEachModifier(slot, consumer) visits each entry whose
// Slot group test accepts the equipment slot. The tooltip-only "display" sub-object is omitted
// (zero gameplay data).
type ItemAttributeModifier struct {
	// Attribute is the target attribute's resource id (e.g. "minecraft:attack_damage").
	Attribute string
	// ID is the modifier's stable identity (e.g. "minecraft:base_attack_damage") — the
	// AttributeInstance modifier-map key.
	ID string
	// Amount is AttributeModifier.amount (a double; meaning depends on Operation).
	Amount float64
	// Operation is the AttributeModifier$Operation enum id: 0 ADD_VALUE, 1 ADD_MULTIPLIED_BASE,
	// 2 ADD_MULTIPLIED_TOTAL.
	Operation int32
	// Slot is the EquipmentSlotGroup serialized key ("any", "mainhand", "offhand", "hand",
	// "feet", "legs", "chest", "head", "armor", "body", "saddle").
	Slot string
}

// AttributeModifiers maps an item resource id (e.g. "minecraft:diamond_sword") to its default
// attribute-modifier entries. Only items that carry an ATTRIBUTE_MODIFIERS component appear here
// (a missing lookup means "no default modifiers" — ItemAttributeModifiers.EMPTY). Keyed by the
// registry resource string so a numeric item id -> Item.Name -> "minecraft:<name>" lookup
// resolves it (see server.itemAttributeModifiers).
var AttributeModifiers = map[string][]ItemAttributeModifier{
	"minecraft:carved_pumpkin": {
		{Attribute: "minecraft:waypoint_transmit_range", ID: "minecraft:waypoint_transmit_range_hide", Amount: -1.0, Operation: 2, Slot: "head"},
	},
	"minecraft:chainmail_boots": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.boots", Amount: 1.0, Operation: 0, Slot: "feet"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.boots", Amount: 0.0, Operation: 0, Slot: "feet"},
	},
	"minecraft:chainmail_chestplate": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.chestplate", Amount: 5.0, Operation: 0, Slot: "chest"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.chestplate", Amount: 0.0, Operation: 0, Slot: "chest"},
	},
	"minecraft:chainmail_helmet": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.helmet", Amount: 2.0, Operation: 0, Slot: "head"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.helmet", Amount: 0.0, Operation: 0, Slot: "head"},
	},
	"minecraft:chainmail_leggings": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.leggings", Amount: 4.0, Operation: 0, Slot: "legs"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.leggings", Amount: 0.0, Operation: 0, Slot: "legs"},
	},
	"minecraft:copper_axe": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 8.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -3.200000047683716, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:copper_boots": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.boots", Amount: 1.0, Operation: 0, Slot: "feet"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.boots", Amount: 0.0, Operation: 0, Slot: "feet"},
	},
	"minecraft:copper_chestplate": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.chestplate", Amount: 4.0, Operation: 0, Slot: "chest"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.chestplate", Amount: 0.0, Operation: 0, Slot: "chest"},
	},
	"minecraft:copper_helmet": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.helmet", Amount: 2.0, Operation: 0, Slot: "head"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.helmet", Amount: 0.0, Operation: 0, Slot: "head"},
	},
	"minecraft:copper_hoe": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 0.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -2.0, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:copper_horse_armor": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.body", Amount: 4.0, Operation: 0, Slot: "body"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.body", Amount: 0.0, Operation: 0, Slot: "body"},
	},
	"minecraft:copper_leggings": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.leggings", Amount: 3.0, Operation: 0, Slot: "legs"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.leggings", Amount: 0.0, Operation: 0, Slot: "legs"},
	},
	"minecraft:copper_nautilus_armor": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.body", Amount: 4.0, Operation: 0, Slot: "body"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.body", Amount: 0.0, Operation: 0, Slot: "body"},
	},
	"minecraft:copper_pickaxe": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 2.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -2.799999952316284, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:copper_shovel": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 2.5, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -3.0, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:copper_spear": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 1.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -2.8235294818878174, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:copper_sword": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 4.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -2.4000000953674316, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:creeper_head": {
		{Attribute: "minecraft:waypoint_transmit_range", ID: "minecraft:waypoint_transmit_range_hide", Amount: -1.0, Operation: 2, Slot: "head"},
	},
	"minecraft:diamond_axe": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 8.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -3.0, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:diamond_boots": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.boots", Amount: 3.0, Operation: 0, Slot: "feet"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.boots", Amount: 2.0, Operation: 0, Slot: "feet"},
	},
	"minecraft:diamond_chestplate": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.chestplate", Amount: 8.0, Operation: 0, Slot: "chest"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.chestplate", Amount: 2.0, Operation: 0, Slot: "chest"},
	},
	"minecraft:diamond_helmet": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.helmet", Amount: 3.0, Operation: 0, Slot: "head"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.helmet", Amount: 2.0, Operation: 0, Slot: "head"},
	},
	"minecraft:diamond_hoe": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 0.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: 0.0, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:diamond_horse_armor": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.body", Amount: 11.0, Operation: 0, Slot: "body"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.body", Amount: 2.0, Operation: 0, Slot: "body"},
	},
	"minecraft:diamond_leggings": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.leggings", Amount: 6.0, Operation: 0, Slot: "legs"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.leggings", Amount: 2.0, Operation: 0, Slot: "legs"},
	},
	"minecraft:diamond_nautilus_armor": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.body", Amount: 11.0, Operation: 0, Slot: "body"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.body", Amount: 2.0, Operation: 0, Slot: "body"},
	},
	"minecraft:diamond_pickaxe": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 4.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -2.799999952316284, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:diamond_shovel": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 4.5, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -3.0, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:diamond_spear": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 3.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -3.0476189851760864, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:diamond_sword": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 6.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -2.4000000953674316, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:dragon_head": {
		{Attribute: "minecraft:waypoint_transmit_range", ID: "minecraft:waypoint_transmit_range_hide", Amount: -1.0, Operation: 2, Slot: "head"},
	},
	"minecraft:golden_axe": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 6.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -3.0, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:golden_boots": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.boots", Amount: 1.0, Operation: 0, Slot: "feet"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.boots", Amount: 0.0, Operation: 0, Slot: "feet"},
	},
	"minecraft:golden_chestplate": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.chestplate", Amount: 5.0, Operation: 0, Slot: "chest"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.chestplate", Amount: 0.0, Operation: 0, Slot: "chest"},
	},
	"minecraft:golden_helmet": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.helmet", Amount: 2.0, Operation: 0, Slot: "head"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.helmet", Amount: 0.0, Operation: 0, Slot: "head"},
	},
	"minecraft:golden_hoe": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 0.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -3.0, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:golden_horse_armor": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.body", Amount: 7.0, Operation: 0, Slot: "body"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.body", Amount: 0.0, Operation: 0, Slot: "body"},
	},
	"minecraft:golden_leggings": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.leggings", Amount: 3.0, Operation: 0, Slot: "legs"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.leggings", Amount: 0.0, Operation: 0, Slot: "legs"},
	},
	"minecraft:golden_nautilus_armor": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.body", Amount: 7.0, Operation: 0, Slot: "body"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.body", Amount: 0.0, Operation: 0, Slot: "body"},
	},
	"minecraft:golden_pickaxe": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 1.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -2.799999952316284, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:golden_shovel": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 1.5, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -3.0, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:golden_spear": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 0.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -2.9473683834075928, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:golden_sword": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 3.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -2.4000000953674316, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:iron_axe": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 8.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -3.0999999046325684, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:iron_boots": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.boots", Amount: 2.0, Operation: 0, Slot: "feet"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.boots", Amount: 0.0, Operation: 0, Slot: "feet"},
	},
	"minecraft:iron_chestplate": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.chestplate", Amount: 6.0, Operation: 0, Slot: "chest"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.chestplate", Amount: 0.0, Operation: 0, Slot: "chest"},
	},
	"minecraft:iron_helmet": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.helmet", Amount: 2.0, Operation: 0, Slot: "head"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.helmet", Amount: 0.0, Operation: 0, Slot: "head"},
	},
	"minecraft:iron_hoe": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 0.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -1.0, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:iron_horse_armor": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.body", Amount: 5.0, Operation: 0, Slot: "body"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.body", Amount: 0.0, Operation: 0, Slot: "body"},
	},
	"minecraft:iron_leggings": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.leggings", Amount: 5.0, Operation: 0, Slot: "legs"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.leggings", Amount: 0.0, Operation: 0, Slot: "legs"},
	},
	"minecraft:iron_nautilus_armor": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.body", Amount: 5.0, Operation: 0, Slot: "body"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.body", Amount: 0.0, Operation: 0, Slot: "body"},
	},
	"minecraft:iron_pickaxe": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 3.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -2.799999952316284, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:iron_shovel": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 3.5, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -3.0, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:iron_spear": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 2.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -2.9473683834075928, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:iron_sword": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 5.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -2.4000000953674316, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:leather_boots": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.boots", Amount: 1.0, Operation: 0, Slot: "feet"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.boots", Amount: 0.0, Operation: 0, Slot: "feet"},
	},
	"minecraft:leather_chestplate": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.chestplate", Amount: 3.0, Operation: 0, Slot: "chest"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.chestplate", Amount: 0.0, Operation: 0, Slot: "chest"},
	},
	"minecraft:leather_helmet": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.helmet", Amount: 1.0, Operation: 0, Slot: "head"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.helmet", Amount: 0.0, Operation: 0, Slot: "head"},
	},
	"minecraft:leather_horse_armor": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.body", Amount: 3.0, Operation: 0, Slot: "body"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.body", Amount: 0.0, Operation: 0, Slot: "body"},
	},
	"minecraft:leather_leggings": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.leggings", Amount: 2.0, Operation: 0, Slot: "legs"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.leggings", Amount: 0.0, Operation: 0, Slot: "legs"},
	},
	"minecraft:mace": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 5.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -3.4000000953674316, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:netherite_axe": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 9.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -3.0, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:netherite_boots": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.boots", Amount: 3.0, Operation: 0, Slot: "feet"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.boots", Amount: 3.0, Operation: 0, Slot: "feet"},
		{Attribute: "minecraft:knockback_resistance", ID: "minecraft:armor.boots", Amount: 0.10000000149011612, Operation: 0, Slot: "feet"},
	},
	"minecraft:netherite_chestplate": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.chestplate", Amount: 8.0, Operation: 0, Slot: "chest"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.chestplate", Amount: 3.0, Operation: 0, Slot: "chest"},
		{Attribute: "minecraft:knockback_resistance", ID: "minecraft:armor.chestplate", Amount: 0.10000000149011612, Operation: 0, Slot: "chest"},
	},
	"minecraft:netherite_helmet": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.helmet", Amount: 3.0, Operation: 0, Slot: "head"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.helmet", Amount: 3.0, Operation: 0, Slot: "head"},
		{Attribute: "minecraft:knockback_resistance", ID: "minecraft:armor.helmet", Amount: 0.10000000149011612, Operation: 0, Slot: "head"},
	},
	"minecraft:netherite_hoe": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 0.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: 0.0, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:netherite_horse_armor": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.body", Amount: 19.0, Operation: 0, Slot: "body"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.body", Amount: 3.0, Operation: 0, Slot: "body"},
		{Attribute: "minecraft:knockback_resistance", ID: "minecraft:armor.body", Amount: 0.10000000149011612, Operation: 0, Slot: "body"},
	},
	"minecraft:netherite_leggings": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.leggings", Amount: 6.0, Operation: 0, Slot: "legs"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.leggings", Amount: 3.0, Operation: 0, Slot: "legs"},
		{Attribute: "minecraft:knockback_resistance", ID: "minecraft:armor.leggings", Amount: 0.10000000149011612, Operation: 0, Slot: "legs"},
	},
	"minecraft:netherite_nautilus_armor": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.body", Amount: 19.0, Operation: 0, Slot: "body"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.body", Amount: 3.0, Operation: 0, Slot: "body"},
		{Attribute: "minecraft:knockback_resistance", ID: "minecraft:armor.body", Amount: 0.10000000149011612, Operation: 0, Slot: "body"},
	},
	"minecraft:netherite_pickaxe": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 5.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -2.799999952316284, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:netherite_shovel": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 5.5, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -3.0, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:netherite_spear": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 4.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -3.13043475151062, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:netherite_sword": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 7.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -2.4000000953674316, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:piglin_head": {
		{Attribute: "minecraft:waypoint_transmit_range", ID: "minecraft:waypoint_transmit_range_hide", Amount: -1.0, Operation: 2, Slot: "head"},
	},
	"minecraft:player_head": {
		{Attribute: "minecraft:waypoint_transmit_range", ID: "minecraft:waypoint_transmit_range_hide", Amount: -1.0, Operation: 2, Slot: "head"},
	},
	"minecraft:skeleton_skull": {
		{Attribute: "minecraft:waypoint_transmit_range", ID: "minecraft:waypoint_transmit_range_hide", Amount: -1.0, Operation: 2, Slot: "head"},
	},
	"minecraft:stone_axe": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 8.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -3.200000047683716, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:stone_hoe": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 0.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -2.0, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:stone_pickaxe": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 2.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -2.799999952316284, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:stone_shovel": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 2.5, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -3.0, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:stone_spear": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 1.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -2.666666626930237, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:stone_sword": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 4.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -2.4000000953674316, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:trident": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 8.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -2.9000000953674316, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:turtle_helmet": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.helmet", Amount: 2.0, Operation: 0, Slot: "head"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.helmet", Amount: 0.0, Operation: 0, Slot: "head"},
	},
	"minecraft:wither_skeleton_skull": {
		{Attribute: "minecraft:waypoint_transmit_range", ID: "minecraft:waypoint_transmit_range_hide", Amount: -1.0, Operation: 2, Slot: "head"},
	},
	"minecraft:wolf_armor": {
		{Attribute: "minecraft:armor", ID: "minecraft:armor.body", Amount: 11.0, Operation: 0, Slot: "body"},
		{Attribute: "minecraft:armor_toughness", ID: "minecraft:armor.body", Amount: 0.0, Operation: 0, Slot: "body"},
	},
	"minecraft:wooden_axe": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 6.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -3.200000047683716, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:wooden_hoe": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 0.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -3.0, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:wooden_pickaxe": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 1.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -2.799999952316284, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:wooden_shovel": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 1.5, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -3.0, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:wooden_spear": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 0.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -2.4615384340286255, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:wooden_sword": {
		{Attribute: "minecraft:attack_damage", ID: "minecraft:base_attack_damage", Amount: 3.0, Operation: 0, Slot: "mainhand"},
		{Attribute: "minecraft:attack_speed", ID: "minecraft:base_attack_speed", Amount: -2.4000000953674316, Operation: 0, Slot: "mainhand"},
	},
	"minecraft:zombie_head": {
		{Attribute: "minecraft:waypoint_transmit_range", ID: "minecraft:waypoint_transmit_range_hide", Amount: -1.0, Operation: 2, Slot: "head"},
	},
}
