// Code generated by tools/gen_item_consume.go from 26.2/items.json; DO NOT EDIT.

package item

// ItemConsumable carries an item CONSUMABLE default-component data beyond the bare FOOD
// nutrition/saturation (data/item/food.go): the Consumable.onConsumeEffects list applied in
// Consumable.onConsume, and the OminousBottleAmplifier ConsumableListener value (bad_omen).
// Keyed by the item resource id ("minecraft:golden_apple"). An item present in this table is
// consumable (usable via right-click) even if it carries no FOOD component (milk_bucket,
// ominous_bottle). See server.finishUsingItem.
type ItemConsumable struct {
	// HasFood reports whether the item carries a FOOD component (FoodData.eat runs only then).
	HasFood bool
	// CanAlwaysEat is FoodProperties.canAlwaysEat() (false when HasFood is false). Consumable.canConsume
	// -> Player.canEat(canAlwaysEat): a canAlwaysEat item (or a no-food consumable) can be used at full hunger.
	CanAlwaysEat bool
	// ConsumeSeconds is Consumable.consumeSeconds() (DEFAULT_CONSUME_SECONDS 1.6f unless overridden;
	// honey_bottle 2.0f). consumeTicks = (int)(ConsumeSeconds * 20.0f).
	ConsumeSeconds   float32
	OnConsumeEffects []ConsumeEffect
	// OminousBottleAmplifier is the OminousBottleAmplifier component value (nil when absent). When
	// set, Consumable.onConsume ConsumableListener adds MobEffects.BAD_OMEN (duration 120000,
	// amplifier == this value, ambient=false, visible=false, showIcon=true).
	OminousBottleAmplifier *int
}

// ConsumeEffectKind discriminates a ConsumeEffect (net.minecraft.world.item.consume_effects.*).
type ConsumeEffectKind int

const (
	ConsumeApplyEffects     ConsumeEffectKind = iota // ApplyStatusEffectsConsumeEffect
	ConsumeRemoveEffects                             // RemoveStatusEffectsConsumeEffect
	ConsumeClearAllEffects                           // ClearAllStatusEffectsConsumeEffect
	ConsumeTeleportRandomly                          // TeleportRandomlyConsumeEffect
	ConsumePlaySound                                 // PlaySoundConsumeEffect
)

// ConsumeEffect is one flattened Consumable.onConsumeEffects entry (a ConsumeEffect record).
type ConsumeEffect struct {
	Kind ConsumeEffectKind
	// ApplyEffects / Probability: ConsumeApplyEffects. Probability is the ApplyStatusEffects
	// DEFAULT_PROBABILITY 1.0f unless overridden (chicken 0.3, poisonous_potato 0.6, rotten_flesh 0.8).
	ApplyEffects []EffectInstance
	Probability  float32
	// RemoveEffects: ConsumeRemoveEffects (the effect ids to remove; honey_bottle -> poison).
	RemoveEffects []string
	// Diameter: ConsumeTeleportRandomly (DEFAULT_DIAMETER 16.0f).
	Diameter float32
	// Sound: ConsumePlaySound (the sound id; server-side v1 no-op).
	Sound string
}

// EffectInstance is a MobEffectInstance carried by an ApplyStatusEffectsConsumeEffect.
type EffectInstance struct {
	ID        string
	Amplifier int
	Duration  int
	Ambient   bool
	Visible   bool
	ShowIcon  bool
}

func intPtr(v int) *int { return &v }

var Consumable = map[string]ItemConsumable{
	"minecraft:apple": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:baked_potato": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:beef": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:beetroot": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:beetroot_soup": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:bread": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:carrot": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:chicken": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
		OnConsumeEffects: []ConsumeEffect{
			{Kind: ConsumeApplyEffects, Probability: 0.3, ApplyEffects: []EffectInstance{
				{ID: "minecraft:hunger", Amplifier: 0, Duration: 600, Ambient: false, Visible: true, ShowIcon: true},
			}},
		},
	},
	"minecraft:chorus_fruit": {
		HasFood: true, CanAlwaysEat: true, ConsumeSeconds: 1.6,
		OnConsumeEffects: []ConsumeEffect{
			{Kind: ConsumeTeleportRandomly, Diameter: 16.0},
		},
	},
	"minecraft:cod": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:cooked_beef": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:cooked_chicken": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:cooked_cod": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:cooked_mutton": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:cooked_porkchop": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:cooked_rabbit": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:cooked_salmon": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:cookie": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:dried_kelp": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 0.8,
	},
	"minecraft:enchanted_golden_apple": {
		HasFood: true, CanAlwaysEat: true, ConsumeSeconds: 1.6,
		OnConsumeEffects: []ConsumeEffect{
			{Kind: ConsumeApplyEffects, Probability: 1.0, ApplyEffects: []EffectInstance{
				{ID: "minecraft:regeneration", Amplifier: 1, Duration: 400, Ambient: false, Visible: true, ShowIcon: true},
				{ID: "minecraft:resistance", Amplifier: 0, Duration: 6000, Ambient: false, Visible: true, ShowIcon: true},
				{ID: "minecraft:fire_resistance", Amplifier: 0, Duration: 6000, Ambient: false, Visible: true, ShowIcon: true},
				{ID: "minecraft:absorption", Amplifier: 3, Duration: 2400, Ambient: false, Visible: true, ShowIcon: true},
			}},
		},
	},
	"minecraft:glow_berries": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:golden_apple": {
		HasFood: true, CanAlwaysEat: true, ConsumeSeconds: 1.6,
		OnConsumeEffects: []ConsumeEffect{
			{Kind: ConsumeApplyEffects, Probability: 1.0, ApplyEffects: []EffectInstance{
				{ID: "minecraft:regeneration", Amplifier: 1, Duration: 100, Ambient: false, Visible: true, ShowIcon: true},
				{ID: "minecraft:absorption", Amplifier: 0, Duration: 2400, Ambient: false, Visible: true, ShowIcon: true},
			}},
		},
	},
	"minecraft:golden_carrot": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:honey_bottle": {
		HasFood: true, CanAlwaysEat: true, ConsumeSeconds: 2.0,
		OnConsumeEffects: []ConsumeEffect{
			{Kind: ConsumeRemoveEffects, RemoveEffects: []string{"minecraft:poison"}},
		},
	},
	"minecraft:melon_slice": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:milk_bucket": {
		HasFood: false, CanAlwaysEat: false, ConsumeSeconds: 1.6,
		OnConsumeEffects: []ConsumeEffect{
			{Kind: ConsumeClearAllEffects},
		},
	},
	"minecraft:mushroom_stew": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:mutton": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:ominous_bottle": {
		HasFood: false, CanAlwaysEat: false, ConsumeSeconds: 1.6,
		OminousBottleAmplifier: intPtr(0),
		OnConsumeEffects: []ConsumeEffect{
			{Kind: ConsumePlaySound, Sound: "minecraft:item.ominous_bottle.dispose"},
		},
	},
	"minecraft:poisonous_potato": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
		OnConsumeEffects: []ConsumeEffect{
			{Kind: ConsumeApplyEffects, Probability: 0.6, ApplyEffects: []EffectInstance{
				{ID: "minecraft:poison", Amplifier: 0, Duration: 100, Ambient: false, Visible: true, ShowIcon: true},
			}},
		},
	},
	"minecraft:porkchop": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:potato": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:potion": {
		HasFood: false, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:pufferfish": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
		OnConsumeEffects: []ConsumeEffect{
			{Kind: ConsumeApplyEffects, Probability: 1.0, ApplyEffects: []EffectInstance{
				{ID: "minecraft:poison", Amplifier: 1, Duration: 1200, Ambient: false, Visible: true, ShowIcon: true},
				{ID: "minecraft:hunger", Amplifier: 2, Duration: 300, Ambient: false, Visible: true, ShowIcon: true},
				{ID: "minecraft:nausea", Amplifier: 0, Duration: 300, Ambient: false, Visible: true, ShowIcon: true},
			}},
		},
	},
	"minecraft:pumpkin_pie": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:rabbit": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:rabbit_stew": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:rotten_flesh": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
		OnConsumeEffects: []ConsumeEffect{
			{Kind: ConsumeApplyEffects, Probability: 0.8, ApplyEffects: []EffectInstance{
				{ID: "minecraft:hunger", Amplifier: 0, Duration: 600, Ambient: false, Visible: true, ShowIcon: true},
			}},
		},
	},
	"minecraft:salmon": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:spider_eye": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
		OnConsumeEffects: []ConsumeEffect{
			{Kind: ConsumeApplyEffects, Probability: 1.0, ApplyEffects: []EffectInstance{
				{ID: "minecraft:poison", Amplifier: 0, Duration: 100, Ambient: false, Visible: true, ShowIcon: true},
			}},
		},
	},
	"minecraft:suspicious_stew": {
		HasFood: true, CanAlwaysEat: true, ConsumeSeconds: 1.6,
	},
	"minecraft:sweet_berries": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
	"minecraft:tropical_fish": {
		HasFood: true, CanAlwaysEat: false, ConsumeSeconds: 1.6,
	},
}
