// Code generated by tools/gen_item_food.go from 26.2/items.json; DO NOT EDIT.

package item

// ItemFood carries an item's FOOD + CONSUMABLE default-component data, taken from the item's
// default DataComponentMap (FoodProperties.nutrition()/saturation()/canAlwaysEat() +
// Consumable.consumeSeconds()). Saturation is the ABSOLUTE saturation value
// (net.minecraft.world.food.FoodData.eat(FoodProperties) calls add(nutrition, saturation)
// directly — NOT FoodConstants.saturationByModifier, so do NOT double it). ConsumeSeconds*20.0f
// (f2i) is the use-duration in ticks (net.minecraft.world.item.component.Consumable.consumeTicks).
type ItemFood struct {
	Nutrition      int32
	Saturation     float32
	CanAlwaysEat   bool
	ConsumeSeconds float32
}

// Food maps an item resource id (e.g. "minecraft:cooked_beef") to its FOOD/CONSUMABLE data.
// Only items that carry a FOOD component appear here (non-food items are absent, so a missing
// lookup means "not eatable"). Keyed by the registry resource string so a numeric item id ->
// Item.Name -> "minecraft:<name>" lookup resolves it (see server.itemFood).
var Food = map[string]ItemFood{
	"minecraft:apple":                  {Nutrition: 4, Saturation: 2.4, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:baked_potato":           {Nutrition: 5, Saturation: 6.0, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:beef":                   {Nutrition: 3, Saturation: 1.8000001, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:beetroot":               {Nutrition: 1, Saturation: 1.2, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:beetroot_soup":          {Nutrition: 6, Saturation: 7.2000003, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:bread":                  {Nutrition: 5, Saturation: 6.0, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:carrot":                 {Nutrition: 3, Saturation: 3.6000001, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:chicken":                {Nutrition: 2, Saturation: 1.2, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:chorus_fruit":           {Nutrition: 4, Saturation: 2.4, CanAlwaysEat: true, ConsumeSeconds: 1.6},
	"minecraft:cod":                    {Nutrition: 2, Saturation: 0.4, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:cod_bucket":             {Nutrition: 2, Saturation: 0.4, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:cooked_beef":            {Nutrition: 8, Saturation: 12.8, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:cooked_chicken":         {Nutrition: 6, Saturation: 7.2000003, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:cooked_cod":             {Nutrition: 5, Saturation: 6.0, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:cooked_mutton":          {Nutrition: 6, Saturation: 9.6, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:cooked_porkchop":        {Nutrition: 8, Saturation: 12.8, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:cooked_rabbit":          {Nutrition: 5, Saturation: 6.0, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:cooked_salmon":          {Nutrition: 6, Saturation: 9.6, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:cookie":                 {Nutrition: 2, Saturation: 0.4, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:dried_kelp":             {Nutrition: 1, Saturation: 0.6, CanAlwaysEat: false, ConsumeSeconds: 0.8},
	"minecraft:enchanted_golden_apple": {Nutrition: 4, Saturation: 9.6, CanAlwaysEat: true, ConsumeSeconds: 1.6},
	"minecraft:glow_berries":           {Nutrition: 2, Saturation: 0.4, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:golden_apple":           {Nutrition: 4, Saturation: 9.6, CanAlwaysEat: true, ConsumeSeconds: 1.6},
	"minecraft:golden_carrot":          {Nutrition: 6, Saturation: 14.400001, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:honey_bottle":           {Nutrition: 6, Saturation: 1.2, CanAlwaysEat: true, ConsumeSeconds: 2.0},
	"minecraft:melon_slice":            {Nutrition: 2, Saturation: 1.2, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:mushroom_stew":          {Nutrition: 6, Saturation: 7.2000003, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:mutton":                 {Nutrition: 2, Saturation: 1.2, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:poisonous_potato":       {Nutrition: 2, Saturation: 1.2, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:porkchop":               {Nutrition: 3, Saturation: 1.8000001, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:potato":                 {Nutrition: 1, Saturation: 0.6, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:pufferfish":             {Nutrition: 1, Saturation: 0.2, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:pufferfish_bucket":      {Nutrition: 1, Saturation: 0.2, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:pumpkin_pie":            {Nutrition: 8, Saturation: 4.8, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:rabbit":                 {Nutrition: 3, Saturation: 1.8000001, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:rabbit_stew":            {Nutrition: 10, Saturation: 12.0, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:rotten_flesh":           {Nutrition: 4, Saturation: 0.8, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:salmon":                 {Nutrition: 2, Saturation: 0.4, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:salmon_bucket":          {Nutrition: 2, Saturation: 0.4, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:spider_eye":             {Nutrition: 2, Saturation: 3.2, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:suspicious_stew":        {Nutrition: 6, Saturation: 7.2000003, CanAlwaysEat: true, ConsumeSeconds: 1.6},
	"minecraft:sweet_berries":          {Nutrition: 2, Saturation: 0.4, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:tropical_fish":          {Nutrition: 1, Saturation: 0.2, CanAlwaysEat: false, ConsumeSeconds: 1.6},
	"minecraft:tropical_fish_bucket":   {Nutrition: 1, Saturation: 0.2, CanAlwaysEat: false, ConsumeSeconds: 1.6},
}
