package server

// consume_effects.go is the 1:1 port of the CONSUMABLE onConsume effect-application chain: the
// ConsumableListener iteration (FoodProperties.onConsume eat + OminousBottleAmplifier.onConsume
// bad_omen) and the server-side onConsumeEffects list (the ConsumeEffect records). It is the seam
// item_use.go finishUsingItem calls AFTER FoodData.eat, so a completed eat/drink applies every
// declared status effect, removal, clear, or chorus teleport.
//
// The per-item ConsumeEffect data is DATA-DRIVEN, read from data/item/consume.go (generated by
// tools/gen_item_consume.go from the jar items.json report), so nothing here is hardcoded per item:
// the effect ids, durations, amplifiers, and probabilities all come from the item CONSUMABLE
// component exactly as the vanilla codec loaded them.
//
// Cited bytecode (FQCN.method), verified via javap -c -p on temp/cache/26.2-inner.jar this session:
//
//	Consumable.onConsume(Level, LivingEntity, ItemStack): emitParticlesAndSounds (v1 no-op); if
//	    ServerPlayer awardStat + CONSUME_ITEM trigger (no-op); getAllOfType(ConsumableListener).forEach
//	    (l.onConsume); if (!isClientSide) onConsumeEffects.forEach(e.apply); gameEvent(EAT/DRINK)
//	    (no-op); stack.consume(1, entity).
//	FoodProperties.onConsume: if Player p.getFoodData().eat(this) [ported in finishUsingItem] + sounds.
//	OminousBottleAmplifier.onConsume: addEffect(new MobEffectInstance(BAD_OMEN, 120000, value, false,
//	    false, true)).
//	ApplyStatusEffectsConsumeEffect.apply: if (getRandom().nextFloat() >= probability) return false;
//	    for e in effects addEffect(new MobEffectInstance(e)); return anyAdded.
//	RemoveStatusEffectsConsumeEffect.apply: for h in effects removeEffect(h); return anyRemoved.
//	ClearAllStatusEffectsConsumeEffect.apply: return removeAllEffects().
//	TeleportRandomlyConsumeEffect.apply (diameter default 16.0f): 16 tries; per try x = getX()+
//	    (nextDouble()-0.5)*diameter, y = clamp(getY()+(nextDouble()-0.5)*diameter, minY, minY+
//	    logicalHeight-1), z = getZ()+(nextDouble()-0.5)*diameter; if randomTeleport(x,y,z,true)
//	    { gameEvent(TELEPORT); playSound(CHORUS_FRUIT_TELEPORT); resetFallDistance(); break; };
//	    if teleported resetCurrentImpulseContext().
//	LivingEntity.randomTeleport(x,y,z,broadcast): step down from BlockPos.containing(x,y,z) while
//	    below.blocksMotion()==false and y>minY (decrementing y); if ground found teleportTo(x,y,z) and
//	    noCollision(this) and not containsAnyLiquid(box) -> teleported; else teleportTo(old) return
//	    false; on success+broadcast broadcastEntityEvent(46).
//
// ALL state is tick-owned: applyConsumeEffects runs only from finishUsingItem on the tick goroutine
// over the tick-owned player/effect fields, so it is -race clean by the single-owner discipline of
// the rest of the eat chain.

import (
	"math"

	"github.com/imhinotori/sulfur/data/item"
	pk "github.com/imhinotori/sulfur/net/packet"
	"github.com/imhinotori/sulfur/world/levelgen"
)

// itemConsumable maps a numeric item id to its CONSUMABLE data (data/item/consume.go), resolving
// id -> Item.Name -> "minecraft:<name>" -> the Consumable table, mirroring itemFood. An item absent
// from the table is not consumable (ok=false). Tick-owned read.
func itemConsumable(itemID int32) (item.ItemConsumable, bool) {
	it, ok := item.ByID[item.ID(itemID)]
	if !ok {
		return item.ItemConsumable{}, false
	}
	c, ok := item.Consumable["minecraft:"+it.Name]
	return c, ok
}

// consumeRandom is entity.getRandom() for a player-consume draw (the ApplyStatusEffects probability
// gate + the TeleportRandomly position rolls). Vanilla reads the player Entity.random; v1 uses the
// current region levelRandom (the established tick-time player-facing RNG source, see the witch/cat
// paths), a cited stand-in that preserves observable randomness. The pig oracle never eats, so no
// pig-AI draw shares this stream.
func (t *TickLoop) consumeRandom() *levelgen.LegacyRandomSource {
	if r := t.cur(); r != nil && r.levelRandom != nil {
		return r.levelRandom
	}
	return nil
}

// applyConsumeEffects is the ConsumableListener + onConsumeEffects half of Consumable.onConsume, run
// from finishUsingItem AFTER FoodData.eat and BEFORE stack.consume(1). It applies, in exact vanilla
// order: (1) the OminousBottleAmplifier ConsumableListener (bad_omen), if present, which runs
// UNCONDITIONALLY (not isClientSide-gated); (2) the onConsumeEffects list, which is isClientSide-gated
// and so always runs server-side. Tick-owned.
func (t *TickLoop) applyConsumeEffects(p *tickPlayer, c item.ItemConsumable) {
	// ConsumableListener step: OminousBottleAmplifier.onConsume -> addEffect(BAD_OMEN, 120000, value,
	// ambient=false, visible=false, showIcon=true). (FoodProperties.onConsume, the other listener, is
	// the FoodData.eat already applied in finishUsingItem.)
	if c.OminousBottleAmplifier != nil {
		t.addPlayerEffect(p, 0, effectBadOmen, ominousBottleBadOmenDuration, *c.OminousBottleAmplifier, 1.0)
	}

	// onConsumeEffects.forEach(effect.apply): server-side only (always true here).
	for _, e := range c.OnConsumeEffects {
		switch e.Kind {
		case item.ConsumeApplyEffects:
			t.applyStatusEffectsConsumeEffect(p, e)
		case item.ConsumeRemoveEffects:
			t.removeStatusEffectsConsumeEffect(p, e)
		case item.ConsumeClearAllEffects:
			// ClearAllStatusEffectsConsumeEffect.apply -> LivingEntity.removeAllEffects() (milk_bucket).
			t.playerRemoveAllEffects(p)
		case item.ConsumeTeleportRandomly:
			t.teleportRandomlyConsumeEffect(p, e)
		case item.ConsumePlaySound:
			// PlaySoundConsumeEffect.apply -> level.playSound(...): sound only, v1 no-op (no sound wire).
			// ominous_bottle.dispose: the bad_omen it grants is the OminousBottleAmplifier listener above.
		}
	}
}

// ominousBottleBadOmenDuration is the BAD_OMEN duration OminousBottleAmplifier.onConsume applies
// (ldc int 120000 in the bytecode: 120000 ticks == 100 minutes). The amplifier is the component value.
const ominousBottleBadOmenDuration = 120000

// applyStatusEffectsConsumeEffect ports ApplyStatusEffectsConsumeEffect.apply: roll the probability
// gate (getRandom().nextFloat() >= probability -> skip), then addEffect each MobEffectInstance. The
// nextFloat() draw happens EXACTLY ONCE per effect record, before the loop, matching the bytecode
// (the fcmpl/iflt at offset 13). Tick-owned.
func (t *TickLoop) applyStatusEffectsConsumeEffect(p *tickPlayer, e item.ConsumeEffect) {
	// getRandom().nextFloat() >= probability -> return false. Vanilla always draws (even for a
	// probability-1.0 effect), so the RNG stream advances identically whether or not the effect lands.
	// getRandom().nextFloat() is in [0,1); a nil RNG (no region levelRandom in a unit harness) uses 0.0
	// so a probability-1.0 effect still applies (1.0 > 0.0), matching the guaranteed vanilla apply.
	roll := float32(0.0)
	if r := t.consumeRandom(); r != nil {
		roll = r.NextFloat()
	}
	if roll >= e.Probability {
		return
	}
	for _, m := range e.ApplyEffects {
		// addEffect(new MobEffectInstance(m)): a fresh copy per add. ambient/visible/showIcon are
		// wire/visual-only in v1 and are not read by addPlayerEffect (cited: no UpdateMobEffect wire),
		// so the duration+amplifier are the observable state.
		t.addPlayerEffect(p, 0, m.ID, m.Duration, m.Amplifier, 1.0)
	}
}

// removeStatusEffectsConsumeEffect ports RemoveStatusEffectsConsumeEffect.apply: removeEffect each id
// in the HolderSet (honey_bottle -> poison). Tick-owned.
func (t *TickLoop) removeStatusEffectsConsumeEffect(p *tickPlayer, e item.ConsumeEffect) {
	for _, id := range e.RemoveEffects {
		t.playerRemoveEffect(p, id)
	}
}

// playerRemoveEffect ports LivingEntity.removeEffect(Holder) for a single effect id: removeEffectNoUpdate
// (delete from the active-effect map, capturing whether it was present) then, if present, onEffectsRemoved
// (detach the attribute modifiers + run the removal hook). Mirrors the per-effect body of
// playerRemoveAllEffects. Returns whether an effect was removed. Tick-owned.
func (t *TickLoop) playerRemoveEffect(p *tickPlayer, id string) bool {
	if p == nil || p.activeEffects == nil {
		return false
	}
	if _, ok := p.activeEffects[id]; !ok {
		return false // removeEffectNoUpdate returned null -> no onEffectsRemoved, return false
	}
	delete(p.activeEffects, id)
	t.removeEffectModifiers(p, id) // onEffectsRemoved -> MobEffect.removeAttributeModifiers
	t.onPlayerEffectRemoved(p, id) // + the removal hook (updateInvisibilityStatus etc.)
	return true
}

// teleportRandomlyConsumeEffect ports TeleportRandomlyConsumeEffect.apply for a player (chorus_fruit,
// diameter 16.0f): up to 16 tries at a random offset box, teleporting to the first ground-standable,
// collision-free, non-liquid landing. EXACT RNG draw order per try: nextDouble() for X, then Y, then Z
// (the bytecode evaluates the three coordinate expressions left-to-right). On the first successful
// randomTeleport it fires the teleport particle event (46), resets fall distance, and stops. Tick-owned.
func (t *TickLoop) teleportRandomlyConsumeEffect(p *tickPlayer, e item.ConsumeEffect) {
	diameter := float64(e.Diameter)
	minY := float64(dimMinY)
	// Mth.clamp ceiling: getMinY() + getLogicalHeight() - 1. v1 uses the dimension section span top.
	maxY := float64(dimMaxY) - 1

	for i := 0; i < 16; i++ {
		r := t.consumeRandom()
		var ox, oy, oz float64
		if r != nil {
			ox = r.NextDouble()
			oy = r.NextDouble()
			oz = r.NextDouble()
		} else {
			ox, oy, oz = 0.5, 0.5, 0.5
		}
		x := p.x + (ox-0.5)*diameter
		y := mthClampD(p.y+(oy-0.5)*diameter, minY, maxY)
		z := p.z + (oz-0.5)*diameter
		// isPassenger -> stopRiding(): v1 players are never passengers here (no vehicle mount), no-op.
		if t.playerRandomTeleport(p, x, y, z) {
			// gameEvent(TELEPORT) (no-op); playSound(CHORUS_FRUIT_TELEPORT) (no-op).
			p.resetFallDistance()
			// resetCurrentImpulseContext(): v1 has no per-tick impulse tracking, cited no-op.
			break
		}
	}
}

// playerRandomTeleport ports LivingEntity.randomTeleport(x,y,z,broadcast=true) for a player: step DOWN
// from BlockPos.containing(x,y,z) to the first block whose cell below blocksMotion (isSolidAt),
// decrementing the height as it descends; if a standable ground is found, teleport there iff the player
// box has no solid collision AND contains no liquid; otherwise restore the original position and return
// false. On a broadcast success it fires the teleport particle event (byte 46). Returns whether the
// player was teleported. Tick-owned.
func (t *TickLoop) playerRandomTeleport(p *tickPlayer, x, y, z float64) bool {
	if t.world() == nil {
		return false
	}
	origX, origY, origZ := p.x, p.y, p.z
	height := y
	teleported := false

	bx := int(math.Floor(x))
	bz := int(math.Floor(z))
	// hasChunkAt guard: only search when the target column is loaded (unloaded -> no teleport).
	if _, ok := t.world().GetBlock(pk.Position{X: bx, Y: int(math.Floor(y)), Z: bz}, dimMinY); ok {
		found := false
		cy := int(math.Floor(y))
		for !found && cy > dimMinY {
			// below.blocksMotion(): the cell one below the current probe. isSolidAt == blocksMotion.
			if t.isSolidAt(pk.Position{X: bx, Y: cy - 1, Z: bz}) {
				found = true
			} else {
				height -= 1.0
				cy--
			}
		}
		if found {
			// teleportTo(x, height, z): move the player there, then test the fit.
			p.x, p.y, p.z = x, height, z
			box := playerBoxD(x, height, z)
			if len(t.collectBlockCollisions(box)) == 0 && !t.boxContainsLiquid(box) {
				teleported = true
			}
		}
	}

	if !teleported {
		// teleportTo(oldX,oldY,oldZ): restore and return false.
		p.x, p.y, p.z = origX, origY, origZ
		return false
	}

	// broadcast=true: teleportPlayer sends the authoritative ClientboundPlayerPosition + re-streams the
	// destination ring (the player-facing teleportTo). broadcastEntityEvent(46) shows the teleport
	// particle burst to trackers.
	t.teleportPlayer(p, p.x, p.y, p.z)
	t.broadcastToTrackers(p.entityID, encodeEntityEvent(p.entityID, entityEventTeleport))
	return true
}

// entityEventTeleport is the ClientboundEntityEvent status byte for the teleport particle burst
// (randomTeleport -> broadcastEntityEvent(this, (byte)46); the client handleEntityEvent(46) spawns the
// PORTAL particles at the pre-teleport position).
const entityEventTeleport byte = 46
