package server

import "github.com/imhinotori/sulfur/data/entity"

// entity_track_range.go is the per-type client-tracking-range + update-interval table, a 1:1
// port of the values every EntityType carries via its EntityType.Builder chain
// (net.minecraft.world.entity.EntityTypes static{} register(...) calls: each builder invokes
// .clientTrackingRange(N) and, when it overrides the default, .updateInterval(M)). The go-mc
// generated data/entity table (DO NOT EDIT) does NOT carry these two fields, so they are
// re-expressed here keyed by the generated entity.<Type>.ID -- the authoritative source is the
// jar bytecode (temp/cache/26.2-inner.jar), NOT the community wiki.
//
// The two numbers drive the two vanilla tracker fidelity knobs the flat `trackRange = 6` const
// (tracker.go) collapsed:
//
//   - clientTrackingRange (in CHUNKS): the entity's visibility radius. ChunkMap.addEntity computes
//     range = type.clientTrackingRange() * 16 (blocks); ChunkMap.TrackedEntity.updatePlayer tracks
//     the entity for a player when dx*dx + dz*dz <= min(range, viewDistance*16)^2 (Euclidean,
//     horizontal). A type with clientTrackingRange 0 (marker) is NEVER tracked (addEntity returns
//     early when range == 0).
//   - updateInterval (in TICKS): ServerEntity.sendChanges runs its move/rot body ONLY when
//     tickCount % updateInterval == 0 (|| needsSync || entityData.isDirty()). Most mobs use 3; items/
//     xp/falling_block/tnt 20; arrows 20; projectiles 10; the always-static decorations (painting,
//     item_frame, lightning, area_effect_cloud, end_crystal) use Integer.MAX_VALUE (never a periodic
//     move send -- they move only on an explicit needsSync teleport). Players/mannequin 2; displays 1.
//
//	[VERIFIED javap net.minecraft.world.entity.EntityType$Builder: default clientTrackingRange = 5,
//	 default updateInterval = 3. javap net.minecraft.world.entity.EntityTypes static{}: every
//	 register(ResourceKey, Builder) chain's .clientTrackingRange(N)/.updateInterval(M) args parsed
//	 from the bytecode (bipush/sipush/iconst before each Builder.clientTrackingRange:(I)/
//	 updateInterval:(I) invokevirtual). javap ChunkMap.addEntity: range = clientTrackingRange()*16,
//	 return when 0. javap ChunkMap$TrackedEntity.updatePlayer: d = min(getEffectiveRange(),
//	 viewDistance*16); track when dx^2+dz^2 <= d^2. getEffectiveRange = scaledRange(range);
//	 getScaledTrackingDistance default multiplier 1.0 (range unchanged).]

// trackUpdateNever is EntityType's Integer.MAX_VALUE updateInterval -- the "never send a periodic
// move" sentinel the always-static decorations (painting, item_frame, glow_item_frame, leash_knot,
// lightning_bolt, area_effect_cloud, end_crystal) carry. With tickCount % Integer.MAX_VALUE only
// == 0 at tickCount 0, such an entity broadcasts a move component solely on its first sendChanges
// and thereafter only on an explicit needsSync teleport (never a drift re-anchor from AI motion).
const trackUpdateNever = 2147483647

// trackParams is one EntityType's (clientTrackingRange, updateInterval) pair -- the Builder args.
// Range is in CHUNKS (multiply by 16 for the block radius); interval is in TICKS.
type trackParams struct {
	rangeChunks    int
	updateInterval int
}

// trackParamsByType maps every 26.2 entity type id to its jar-verified (clientTrackingRange,
// updateInterval). Generated by parsing the EntityTypes static{} register chains (see file header);
// 158 entries, complete for the 26.2 registry. A type absent here (never -- the table is complete)
// falls back to the EntityType.Builder defaults via trackParamsFor.
var trackParamsByType = map[entity.ID]trackParams{
	entity.AcaciaBoat.ID:           {10, 3},
	entity.AcaciaChestBoat.ID:      {10, 3},
	entity.Allay.ID:                {8, 2},
	entity.AreaEffectCloud.ID:      {10, trackUpdateNever},
	entity.Armadillo.ID:            {10, 3},
	entity.ArmorStand.ID:           {10, 3},
	entity.Arrow.ID:                {4, 20},
	entity.Axolotl.ID:              {10, 3},
	entity.BambooChestRaft.ID:      {10, 3},
	entity.BambooRaft.ID:           {10, 3},
	entity.Bat.ID:                  {5, 3},
	entity.Bee.ID:                  {8, 3},
	entity.BirchBoat.ID:            {10, 3},
	entity.BirchChestBoat.ID:       {10, 3},
	entity.Blaze.ID:                {8, 3},
	entity.BlockDisplay.ID:         {10, 1},
	entity.Bogged.ID:               {8, 3},
	entity.Breeze.ID:               {10, 3},
	entity.BreezeWindCharge.ID:     {4, 10},
	entity.Camel.ID:                {10, 3},
	entity.CamelHusk.ID:            {10, 3},
	entity.Cat.ID:                  {8, 3},
	entity.CaveSpider.ID:           {8, 3},
	entity.CherryBoat.ID:           {10, 3},
	entity.CherryChestBoat.ID:      {10, 3},
	entity.ChestMinecart.ID:        {8, 3},
	entity.Chicken.ID:              {10, 3},
	entity.Cod.ID:                  {4, 3},
	entity.CommandBlockMinecart.ID: {8, 3},
	entity.CopperGolem.ID:          {10, 3},
	entity.Cow.ID:                  {10, 3},
	entity.Creaking.ID:             {8, 3},
	entity.Creeper.ID:              {8, 3},
	entity.DarkOakBoat.ID:          {10, 3},
	entity.DarkOakChestBoat.ID:     {10, 3},
	entity.Dolphin.ID:              {5, 3},
	entity.Donkey.ID:               {10, 3},
	entity.DragonFireball.ID:       {4, 10},
	entity.Drowned.ID:              {8, 3},
	entity.Egg.ID:                  {4, 10},
	entity.ElderGuardian.ID:        {10, 3},
	entity.EndCrystal.ID:           {16, trackUpdateNever},
	entity.EnderDragon.ID:          {10, 3},
	entity.EnderPearl.ID:           {4, 10},
	entity.Enderman.ID:             {8, 3},
	entity.Endermite.ID:            {8, 3},
	entity.Evoker.ID:               {8, 3},
	entity.EvokerFangs.ID:          {6, 2},
	entity.ExperienceBottle.ID:     {4, 10},
	entity.ExperienceOrb.ID:        {6, 20},
	entity.EyeOfEnder.ID:           {4, 4},
	entity.FallingBlock.ID:         {10, 20},
	entity.Fireball.ID:             {4, 10},
	entity.FireworkRocket.ID:       {4, 10},
	entity.FishingBobber.ID:        {4, 5},
	entity.Fox.ID:                  {8, 3},
	entity.Frog.ID:                 {10, 3},
	entity.FurnaceMinecart.ID:      {8, 3},
	entity.Ghast.ID:                {10, 3},
	entity.Giant.ID:                {10, 3},
	entity.GlowItemFrame.ID:        {10, trackUpdateNever},
	entity.GlowSquid.ID:            {10, 3},
	entity.Goat.ID:                 {10, 3},
	entity.Guardian.ID:             {8, 3},
	entity.HappyGhast.ID:           {10, 3},
	entity.Hoglin.ID:               {8, 3},
	entity.HopperMinecart.ID:       {8, 3},
	entity.Horse.ID:                {10, 3},
	entity.Husk.ID:                 {8, 3},
	entity.Illusioner.ID:           {8, 3},
	entity.Interaction.ID:          {10, 3},
	entity.IronGolem.ID:            {10, 3},
	entity.Item.ID:                 {6, 20},
	entity.ItemDisplay.ID:          {10, 1},
	entity.ItemFrame.ID:            {10, trackUpdateNever},
	entity.JungleBoat.ID:           {10, 3},
	entity.JungleChestBoat.ID:      {10, 3},
	entity.LeashKnot.ID:            {10, trackUpdateNever},
	entity.LightningBolt.ID:        {16, trackUpdateNever},
	entity.LingeringPotion.ID:      {4, 10},
	entity.Llama.ID:                {10, 3},
	entity.LlamaSpit.ID:            {4, 10},
	entity.MagmaCube.ID:            {8, 3},
	entity.MangroveBoat.ID:         {10, 3},
	entity.MangroveChestBoat.ID:    {10, 3},
	entity.Mannequin.ID:            {32, 2},
	entity.Marker.ID:               {0, 3},
	entity.Minecart.ID:             {8, 3},
	entity.Mooshroom.ID:            {10, 3},
	entity.Mule.ID:                 {8, 3},
	entity.Nautilus.ID:             {10, 3},
	entity.OakBoat.ID:              {10, 3},
	entity.OakChestBoat.ID:         {10, 3},
	entity.Ocelot.ID:               {10, 3},
	entity.OminousItemSpawner.ID:   {8, 3},
	entity.Painting.ID:             {10, trackUpdateNever},
	entity.PaleOakBoat.ID:          {10, 3},
	entity.PaleOakChestBoat.ID:     {10, 3},
	entity.Panda.ID:                {10, 3},
	entity.Parched.ID:              {8, 3},
	entity.Parrot.ID:               {8, 3},
	entity.Phantom.ID:              {8, 3},
	entity.Pig.ID:                  {10, 3},
	entity.Piglin.ID:               {8, 3},
	entity.PiglinBrute.ID:          {8, 3},
	entity.Pillager.ID:             {8, 3},
	entity.Player.ID:               {32, 2},
	entity.PolarBear.ID:            {10, 3},
	entity.Pufferfish.ID:           {4, 3},
	entity.Rabbit.ID:               {8, 3},
	entity.Ravager.ID:              {10, 3},
	entity.Salmon.ID:               {4, 3},
	entity.Sheep.ID:                {10, 3},
	entity.Shulker.ID:              {10, 3},
	entity.ShulkerBullet.ID:        {8, 3},
	entity.Silverfish.ID:           {8, 3},
	entity.Skeleton.ID:             {8, 3},
	entity.SkeletonHorse.ID:        {10, 3},
	entity.Slime.ID:                {10, 3},
	entity.SmallFireball.ID:        {4, 10},
	entity.Sniffer.ID:              {10, 3},
	entity.SnowGolem.ID:            {8, 3},
	entity.Snowball.ID:             {4, 10},
	entity.SpawnerMinecart.ID:      {8, 3},
	entity.SpectralArrow.ID:        {4, 20},
	entity.Spider.ID:               {8, 3},
	entity.SplashPotion.ID:         {4, 10},
	entity.SpruceBoat.ID:           {10, 3},
	entity.SpruceChestBoat.ID:      {10, 3},
	entity.Squid.ID:                {8, 3},
	entity.Stray.ID:                {8, 3},
	entity.Strider.ID:              {10, 3},
	entity.SulfurCube.ID:           {10, 3},
	entity.Tadpole.ID:              {10, 3},
	entity.TextDisplay.ID:          {10, 1},
	entity.Tnt.ID:                  {10, 10},
	entity.TntMinecart.ID:          {8, 3},
	entity.TraderLlama.ID:          {10, 3},
	entity.Trident.ID:              {4, 20},
	entity.TropicalFish.ID:         {4, 3},
	entity.Turtle.ID:               {10, 3},
	entity.Vex.ID:                  {8, 3},
	entity.Villager.ID:             {10, 3},
	entity.Vindicator.ID:           {8, 3},
	entity.WanderingTrader.ID:      {10, 3},
	entity.Warden.ID:               {16, 3},
	entity.WindCharge.ID:           {4, 10},
	entity.Witch.ID:                {8, 3},
	entity.Wither.ID:               {10, 3},
	entity.WitherSkeleton.ID:       {8, 3},
	entity.WitherSkull.ID:          {4, 10},
	entity.Wolf.ID:                 {10, 3},
	entity.Zoglin.ID:               {8, 3},
	entity.Zombie.ID:               {8, 3},
	entity.ZombieHorse.ID:          {10, 3},
	entity.ZombieNautilus.ID:       {10, 3},
	entity.ZombieVillager.ID:       {8, 3},
	entity.ZombifiedPiglin.ID:      {8, 3},
}

// trackDefaultRangeChunks / trackDefaultUpdateInterval are the EntityType.Builder ctor defaults
// (clientTrackingRange = 5, updateInterval = 3) -- the fallback for a type absent from the table
// (never in practice; the table is complete for 26.2).
//
//	[VERIFIED javap EntityType$Builder.<init>: iconst_5 putfield clientTrackingRange; iconst_3
//	 putfield updateInterval.]
const (
	trackDefaultRangeChunks      = 5
	trackDefaultUpdateInterval   = 3
	maxClientTrackingRangeChunks = 32 // the largest table value (player/mannequin) -- the broad-phase window
)

// trackParamsFor returns the (clientTrackingRange, updateInterval) for an entity type, falling back
// to the Builder defaults for an unknown type. Cite EntityType.clientTrackingRange/updateInterval.
func trackParamsFor(typ entity.ID) trackParams {
	if tp, ok := trackParamsByType[typ]; ok {
		return tp
	}
	return trackParams{rangeChunks: trackDefaultRangeChunks, updateInterval: trackDefaultUpdateInterval}
}

// entityTrackRangeChunks is the entity's clientTrackingRange in CHUNKS. Cite EntityType.clientTrackingRange.
func entityTrackRangeChunks(typ entity.ID) int { return trackParamsFor(typ).rangeChunks }

// entityUpdateInterval is the entity's updateInterval in TICKS -- the ServerEntity.sendChanges
// tickCount % updateInterval gate. Cite EntityType.updateInterval.
func entityUpdateInterval(typ entity.ID) int { return trackParamsFor(typ).updateInterval }

// entityInTrackRange is the ChunkMap.TrackedEntity.updatePlayer distance gate: an entity is visible
// to a player at (px,pz) with view distance viewDistChunks when the horizontal Euclidean distance in
// BLOCKS satisfies dx*dx + dz*dz <= d*d, where d = min(clientTrackingRange*16, viewDistance*16). A
// type with clientTrackingRange 0 (marker) is never tracked (ChunkMap.addEntity returns early when
// range == 0), so this returns false for it.
//
//	[VERIFIED javap ChunkMap$TrackedEntity.updatePlayer: subtract player-entity pos; d = min(
//	 getEffectiveRange(), getPlayerViewDistance*16); dx*dx + dz*dz (X and Z only) <= d*d. ChunkMap
//	 .addEntity: range = clientTrackingRange()*16; if range == 0 return (untracked).]
func entityInTrackRange(ex, ez, px, pz float64, typ entity.ID, viewDistChunks int) bool {
	rangeChunks := entityTrackRangeChunks(typ)
	if rangeChunks <= 0 {
		return false // clientTrackingRange 0 (marker): never tracked
	}
	rangeBlocks := float64(rangeChunks * 16)
	viewBlocks := float64(viewDistChunks * 16)
	d := rangeBlocks
	if viewBlocks < d {
		d = viewBlocks
	}
	dx := ex - px
	dz := ez - pz
	return dx*dx+dz*dz <= d*d
}
