// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/imhinotori/sulfur/net/packet"
)

var _ DataComponent = (*AxolotlVariant)(nil)

type AxolotlVariant struct{ pk.VarInt }

func (AxolotlVariant) ID() string { return "minecraft:axolotl/variant" }
