// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/imhinotori/sulfur/net/packet"
)

var _ DataComponent = (*BaseColor)(nil)

type BaseColor struct{ pk.VarInt }

func (BaseColor) ID() string { return "minecraft:base_color" }
