// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	"github.com/imhinotori/sulfur/nbt/dynbt"
	pk "github.com/imhinotori/sulfur/net/packet"
)

var _ DataComponent = (*BlockEntityData)(nil)

type BlockEntityData struct {
	Type pk.VarInt
	Data dynbt.Value
}

func (BlockEntityData) ID() string { return "minecraft:block_entity_data" }

func (b *BlockEntityData) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{
		&b.Type,
		pk.NBTField{V: &b.Data, AllowUnknownFields: true},
	}.ReadFrom(r)
}

func (b *BlockEntityData) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{
		&b.Type,
		pk.NBTField{V: &b.Data, AllowUnknownFields: true},
	}.WriteTo(w)
}
