// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/imhinotori/sulfur/net/packet"
)

var _ DataComponent = (*CatVariant)(nil)

type CatVariant struct{ pk.VarInt }

func (CatVariant) ID() string { return "minecraft:cat/variant" }
