// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	"github.com/imhinotori/sulfur/nbt/dynbt"
	pk "github.com/imhinotori/sulfur/net/packet"
)

var _ DataComponent = (*CustomData)(nil)

type CustomData struct{ dynbt.Value }

func (CustomData) ID() string { return "minecraft:custom_data" }

func (c *CustomData) ReadFrom(r io.Reader) (int64, error) {
	return pk.NBT(&c.Value).ReadFrom(r)
}

func (c *CustomData) WriteTo(w io.Writer) (int64, error) {
	return pk.NBT(&c.Value).WriteTo(w)
}
