// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/imhinotori/sulfur/net/packet"
)

var _ DataComponent = (*Dye)(nil)

type Dye struct{ pk.VarInt }

func (Dye) ID() string { return "minecraft:dye" }
