// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/imhinotori/sulfur/net/packet"
)

var _ DataComponent = (*DyedColor)(nil)

type DyedColor struct{ pk.Int }

func (DyedColor) ID() string { return "minecraft:dyed_color" }
