// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/imhinotori/sulfur/net/packet"
)

var _ DataComponent = (*FrogVariant)(nil)

type FrogVariant struct{ pk.VarInt }

func (FrogVariant) ID() string { return "minecraft:frog/variant" }
