// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/imhinotori/sulfur/net/packet"
)

var _ DataComponent = (*HorseVariant)(nil)

type HorseVariant struct{ pk.VarInt }

func (HorseVariant) ID() string { return "minecraft:horse/variant" }
