// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/imhinotori/sulfur/net/packet"
)

var _ DataComponent = (*MapColor)(nil)

type MapColor struct{ pk.Int }

func (MapColor) ID() string { return "minecraft:map_color" }
