// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	"io"

	"github.com/imhinotori/sulfur/nbt/dynbt"
	pk "github.com/imhinotori/sulfur/net/packet"
)

var _ DataComponent = (*MapDecorations)(nil)

type MapDecorations struct{ dynbt.Value }

func (MapDecorations) ID() string { return "minecraft:map_decorations" }

func (m *MapDecorations) ReadFrom(r io.Reader) (int64, error) {
	return pk.NBT(&m.Value).ReadFrom(r)
}

func (m *MapDecorations) WriteTo(w io.Writer) (int64, error) {
	return pk.NBT(&m.Value).WriteTo(w)
}
