// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/imhinotori/sulfur/net/packet"
)

var _ DataComponent = (*MinimumAttackCharge)(nil)

type MinimumAttackCharge struct{ pk.Float }

func (MinimumAttackCharge) ID() string { return "minecraft:minimum_attack_charge" }
