// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/imhinotori/sulfur/net/packet"
)

var _ DataComponent = (*MooshroomVariant)(nil)

type MooshroomVariant struct{ pk.VarInt }

func (MooshroomVariant) ID() string { return "minecraft:mooshroom/variant" }
