// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/imhinotori/sulfur/net/packet"
)

var _ DataComponent = (*RabbitVariant)(nil)

type RabbitVariant struct{ pk.VarInt }

func (RabbitVariant) ID() string { return "minecraft:rabbit/variant" }
