// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/imhinotori/sulfur/net/packet"
)

var _ DataComponent = (*ShulkerColor)(nil)

type ShulkerColor struct{ pk.VarInt }

func (ShulkerColor) ID() string { return "minecraft:shulker/color" }
