// Code generated by tools/gen_tool_defaults.go from 26.2 item component reports; DO NOT EDIT.

package component

// DefaultTool maps an item resource id ("minecraft:diamond_shovel") to its DEFAULT
// minecraft:tool data component — the DataComponents.TOOL value baked into the item at
// registration (vanilla Item.components()). The client sends only the component PATCH
// (deltas from these defaults), so gameplay code that needs an item's mining rules
// (ItemStack.getDestroySpeed / Player.hasCorrectToolForDrops) MUST overlay the wire patch
// on top of this default. An item absent from the map has no TOOL component (a non-tool:
// getMiningSpeed falls through to the empty-hand 1.0 default in the caller). Rule ORDER is
// preserved from the report (isCorrectForDrops / getMiningSpeed take the FIRST matching
// rule). Extracted from temp/cache/26.2-datagen/.../components/item/*.json.
var DefaultTool = map[string]ToolData{
	"minecraft:copper_axe": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_copper_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/axe"}, Speed: 5.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:copper_hoe": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_copper_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/hoe"}, Speed: 5.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:copper_pickaxe": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_copper_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/pickaxe"}, Speed: 5.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:copper_shovel": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_copper_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/shovel"}, Speed: 5.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:copper_sword": {
		Rules: []ToolRuleData{
			{Blocks: []string{"minecraft:cobweb"}, Speed: 15.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:sword_instantly_mines"}, Speed: 3.4028235e+38, HasSpeed: true},
			{Blocks: []string{"#minecraft:sword_efficient"}, Speed: 1.5, HasSpeed: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             2,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:diamond_axe": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_diamond_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/axe"}, Speed: 8.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:diamond_hoe": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_diamond_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/hoe"}, Speed: 8.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:diamond_pickaxe": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_diamond_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/pickaxe"}, Speed: 8.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:diamond_shovel": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_diamond_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/shovel"}, Speed: 8.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:diamond_sword": {
		Rules: []ToolRuleData{
			{Blocks: []string{"minecraft:cobweb"}, Speed: 15.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:sword_instantly_mines"}, Speed: 3.4028235e+38, HasSpeed: true},
			{Blocks: []string{"#minecraft:sword_efficient"}, Speed: 1.5, HasSpeed: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             2,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:golden_axe": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_gold_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/axe"}, Speed: 12.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:golden_hoe": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_gold_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/hoe"}, Speed: 12.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:golden_pickaxe": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_gold_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/pickaxe"}, Speed: 12.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:golden_shovel": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_gold_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/shovel"}, Speed: 12.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:golden_sword": {
		Rules: []ToolRuleData{
			{Blocks: []string{"minecraft:cobweb"}, Speed: 15.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:sword_instantly_mines"}, Speed: 3.4028235e+38, HasSpeed: true},
			{Blocks: []string{"#minecraft:sword_efficient"}, Speed: 1.5, HasSpeed: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             2,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:iron_axe": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_iron_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/axe"}, Speed: 6.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:iron_hoe": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_iron_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/hoe"}, Speed: 6.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:iron_pickaxe": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_iron_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/pickaxe"}, Speed: 6.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:iron_shovel": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_iron_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/shovel"}, Speed: 6.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:iron_sword": {
		Rules: []ToolRuleData{
			{Blocks: []string{"minecraft:cobweb"}, Speed: 15.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:sword_instantly_mines"}, Speed: 3.4028235e+38, HasSpeed: true},
			{Blocks: []string{"#minecraft:sword_efficient"}, Speed: 1.5, HasSpeed: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             2,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:mace": {
		Rules:                      []ToolRuleData{},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             2,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:netherite_axe": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_netherite_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/axe"}, Speed: 9.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:netherite_hoe": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_netherite_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/hoe"}, Speed: 9.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:netherite_pickaxe": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_netherite_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/pickaxe"}, Speed: 9.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:netherite_shovel": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_netherite_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/shovel"}, Speed: 9.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:netherite_sword": {
		Rules: []ToolRuleData{
			{Blocks: []string{"minecraft:cobweb"}, Speed: 15.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:sword_instantly_mines"}, Speed: 3.4028235e+38, HasSpeed: true},
			{Blocks: []string{"#minecraft:sword_efficient"}, Speed: 1.5, HasSpeed: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             2,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:shears": {
		Rules: []ToolRuleData{
			{Blocks: []string{"minecraft:cobweb"}, Speed: 15.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:shears_extreme_breaking_speed"}, Speed: 15.0, HasSpeed: true},
			{Blocks: []string{"#minecraft:shears_major_breaking_speed"}, Speed: 5.0, HasSpeed: true},
			{Blocks: []string{"#minecraft:shears_minor_breaking_speed"}, Speed: 2.0, HasSpeed: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:stone_axe": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_stone_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/axe"}, Speed: 4.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:stone_hoe": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_stone_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/hoe"}, Speed: 4.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:stone_pickaxe": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_stone_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/pickaxe"}, Speed: 4.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:stone_shovel": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_stone_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/shovel"}, Speed: 4.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:stone_sword": {
		Rules: []ToolRuleData{
			{Blocks: []string{"minecraft:cobweb"}, Speed: 15.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:sword_instantly_mines"}, Speed: 3.4028235e+38, HasSpeed: true},
			{Blocks: []string{"#minecraft:sword_efficient"}, Speed: 1.5, HasSpeed: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             2,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:trident": {
		Rules:                      []ToolRuleData{},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             2,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:wooden_axe": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_wooden_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/axe"}, Speed: 2.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:wooden_hoe": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_wooden_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/hoe"}, Speed: 2.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:wooden_pickaxe": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_wooden_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/pickaxe"}, Speed: 2.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:wooden_shovel": {
		Rules: []ToolRuleData{
			{Blocks: []string{"#minecraft:incorrect_for_wooden_tool"}, CorrectForDrops: false, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:mineable/shovel"}, Speed: 2.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             0,
		CanDestroyBlocksInCreative: false,
	},
	"minecraft:wooden_sword": {
		Rules: []ToolRuleData{
			{Blocks: []string{"minecraft:cobweb"}, Speed: 15.0, HasSpeed: true, CorrectForDrops: true, HasCorrectForDrops: true},
			{Blocks: []string{"#minecraft:sword_instantly_mines"}, Speed: 3.4028235e+38, HasSpeed: true},
			{Blocks: []string{"#minecraft:sword_efficient"}, Speed: 1.5, HasSpeed: true},
		},
		DefaultMiningSpeed:         1.0,
		DamagePerBlock:             2,
		CanDestroyBlocksInCreative: false,
	},
}
