// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/imhinotori/sulfur/net/packet"
)

var _ DataComponent = (*TropicalFishPattern)(nil)

type TropicalFishPattern struct{ pk.VarInt }

func (TropicalFishPattern) ID() string { return "minecraft:tropical_fish/pattern" }
