// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/imhinotori/sulfur/net/packet"
)

var _ DataComponent = (*TropicalFishPatternColor)(nil)

type TropicalFishPatternColor struct{ pk.VarInt }

func (TropicalFishPatternColor) ID() string { return "minecraft:tropical_fish/pattern_color" }
