// Code generated by tools/gen_component_types.go from merged component schema; DO NOT EDIT.
package component

import (
	pk "github.com/imhinotori/sulfur/net/packet"
)

var _ DataComponent = (*WolfSoundVariant)(nil)

type WolfSoundVariant struct{ pk.VarInt }

func (WolfSoundVariant) ID() string { return "minecraft:wolf/sound_variant" }
